/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConflictErrorResponseContent
 */
export interface ConflictErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof ConflictErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the ConflictErrorResponseContent interface.
 */
export function instanceOfConflictErrorResponseContent(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function ConflictErrorResponseContentFromJSON(json: any): ConflictErrorResponseContent {
    return ConflictErrorResponseContentFromJSONTyped(json, false);
}

export function ConflictErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConflictErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ConflictErrorResponseContentToJSON(value?: ConflictErrorResponseContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

