/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePullRequestCommentBody
 */
export interface CreatePullRequestCommentBody {
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestCommentBody
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestCommentBody
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePullRequestCommentBody
     */
    lineNumber?: number;
}

/**
 * Check if a given object implements the CreatePullRequestCommentBody interface.
 */
export function instanceOfCreatePullRequestCommentBody(value: object): boolean {
    if (!('body' in value)) return false;
    return true;
}

export function CreatePullRequestCommentBodyFromJSON(json: any): CreatePullRequestCommentBody {
    return CreatePullRequestCommentBodyFromJSONTyped(json, false);
}

export function CreatePullRequestCommentBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePullRequestCommentBody {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
    };
}

export function CreatePullRequestCommentBodyToJSON(value?: CreatePullRequestCommentBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'body': value['body'],
        'filePath': value['filePath'],
        'lineNumber': value['lineNumber'],
    };
}

