/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForbiddenErrorResponseContent
 */
export interface ForbiddenErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof ForbiddenErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the ForbiddenErrorResponseContent interface.
 */
export function instanceOfForbiddenErrorResponseContent(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function ForbiddenErrorResponseContentFromJSON(json: any): ForbiddenErrorResponseContent {
    return ForbiddenErrorResponseContentFromJSONTyped(json, false);
}

export function ForbiddenErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForbiddenErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ForbiddenErrorResponseContentToJSON(value?: ForbiddenErrorResponseContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

