/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalServerErrorResponseContent
 */
export interface InternalServerErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof InternalServerErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the InternalServerErrorResponseContent interface.
 */
export function instanceOfInternalServerErrorResponseContent(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function InternalServerErrorResponseContentFromJSON(json: any): InternalServerErrorResponseContent {
    return InternalServerErrorResponseContentFromJSONTyped(json, false);
}

export function InternalServerErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServerErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function InternalServerErrorResponseContentToJSON(value?: InternalServerErrorResponseContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

