/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PullRequestCommentDTO } from './PullRequestCommentDTO';
import {
    PullRequestCommentDTOFromJSON,
    PullRequestCommentDTOFromJSONTyped,
    PullRequestCommentDTOToJSON,
} from './PullRequestCommentDTO';

/**
 * 
 * @export
 * @interface ListPullRequestCommentsBody
 */
export interface ListPullRequestCommentsBody {
    /**
     * 
     * @type {Array<PullRequestCommentDTO>}
     * @memberof ListPullRequestCommentsBody
     */
    comments: Array<PullRequestCommentDTO>;
}

/**
 * Check if a given object implements the ListPullRequestCommentsBody interface.
 */
export function instanceOfListPullRequestCommentsBody(value: object): boolean {
    if (!('comments' in value)) return false;
    return true;
}

export function ListPullRequestCommentsBodyFromJSON(json: any): ListPullRequestCommentsBody {
    return ListPullRequestCommentsBodyFromJSONTyped(json, false);
}

export function ListPullRequestCommentsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPullRequestCommentsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(PullRequestCommentDTOFromJSON)),
    };
}

export function ListPullRequestCommentsBodyToJSON(value?: ListPullRequestCommentsBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comments': ((value['comments'] as Array<any>).map(PullRequestCommentDTOToJSON)),
    };
}

