/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
} from './AuthorSummary';
import type { PrStatus } from './PrStatus';
import {
    PrStatusFromJSON,
    PrStatusFromJSONTyped,
    PrStatusToJSON,
} from './PrStatus';

/**
 * 
 * @export
 * @interface PullRequestDTO
 */
export interface PullRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    repoId: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequestDTO
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    sourceBranch: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    targetBranch: string;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof PullRequestDTO
     */
    author: AuthorSummary;
    /**
     * 
     * @type {PrStatus}
     * @memberof PullRequestDTO
     */
    status: PrStatus;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestDTO
     */
    hasConflicts: boolean;
    /**
     * 
     * @type {number}
     * @memberof PullRequestDTO
     */
    commitsCount: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    mergedAt?: string;
}

/**
 * Check if a given object implements the PullRequestDTO interface.
 */
export function instanceOfPullRequestDTO(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('repoId' in value)) return false;
    if (!('number' in value)) return false;
    if (!('title' in value)) return false;
    if (!('sourceBranch' in value)) return false;
    if (!('targetBranch' in value)) return false;
    if (!('author' in value)) return false;
    if (!('status' in value)) return false;
    if (!('hasConflicts' in value)) return false;
    if (!('commitsCount' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function PullRequestDTOFromJSON(json: any): PullRequestDTO {
    return PullRequestDTOFromJSONTyped(json, false);
}

export function PullRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'repoId': json['repoId'],
        'number': json['number'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceBranch': json['sourceBranch'],
        'targetBranch': json['targetBranch'],
        'author': AuthorSummaryFromJSON(json['author']),
        'status': PrStatusFromJSON(json['status']),
        'hasConflicts': json['hasConflicts'],
        'commitsCount': json['commitsCount'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'mergedAt': json['mergedAt'] == null ? undefined : json['mergedAt'],
    };
}

export function PullRequestDTOToJSON(value?: PullRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'repoId': value['repoId'],
        'number': value['number'],
        'title': value['title'],
        'description': value['description'],
        'sourceBranch': value['sourceBranch'],
        'targetBranch': value['targetBranch'],
        'author': AuthorSummaryToJSON(value['author']),
        'status': PrStatusToJSON(value['status']),
        'hasConflicts': value['hasConflicts'],
        'commitsCount': value['commitsCount'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'mergedAt': value['mergedAt'],
    };
}

