/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PullRequestMergeabilityDTO
 */
export interface PullRequestMergeabilityDTO {
    /**
     * 
     * @type {number}
     * @memberof PullRequestMergeabilityDTO
     */
    prNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestMergeabilityDTO
     */
    mergeable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestMergeabilityDTO
     */
    hasConflicts: boolean;
    /**
     * 
     * @type {string}
     * @memberof PullRequestMergeabilityDTO
     */
    reason?: string;
}

/**
 * Check if a given object implements the PullRequestMergeabilityDTO interface.
 */
export function instanceOfPullRequestMergeabilityDTO(value: object): boolean {
    if (!('prNumber' in value)) return false;
    if (!('mergeable' in value)) return false;
    if (!('hasConflicts' in value)) return false;
    return true;
}

export function PullRequestMergeabilityDTOFromJSON(json: any): PullRequestMergeabilityDTO {
    return PullRequestMergeabilityDTOFromJSONTyped(json, false);
}

export function PullRequestMergeabilityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestMergeabilityDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'prNumber': json['prNumber'],
        'mergeable': json['mergeable'],
        'hasConflicts': json['hasConflicts'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PullRequestMergeabilityDTOToJSON(value?: PullRequestMergeabilityDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'prNumber': value['prNumber'],
        'mergeable': value['mergeable'],
        'hasConflicts': value['hasConflicts'],
        'reason': value['reason'],
    };
}

