/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
} from './AuthorSummary';

/**
 * 
 * @export
 * @interface PullRequestCommentDTO
 */
export interface PullRequestCommentDTO {
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    pullRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequestCommentDTO
     */
    lineNumber?: number;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof PullRequestCommentDTO
     */
    author: AuthorSummary;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PullRequestCommentDTO interface.
 */
export function instanceOfPullRequestCommentDTO(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('pullRequestId' in value)) return false;
    if (!('body' in value)) return false;
    if (!('author' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    return true;
}

export function PullRequestCommentDTOFromJSON(json: any): PullRequestCommentDTO {
    return PullRequestCommentDTOFromJSONTyped(json, false);
}

export function PullRequestCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestCommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pullRequestId': json['pullRequestId'],
        'body': json['body'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
        'author': AuthorSummaryFromJSON(json['author']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function PullRequestCommentDTOToJSON(value?: PullRequestCommentDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'pullRequestId': value['pullRequestId'],
        'body': value['body'],
        'filePath': value['filePath'],
        'lineNumber': value['lineNumber'],
        'author': AuthorSummaryToJSON(value['author']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

