/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewDecision } from './ReviewDecision';
import {
    ReviewDecisionFromJSON,
    ReviewDecisionFromJSONTyped,
    ReviewDecisionToJSON,
} from './ReviewDecision';

/**
 * 
 * @export
 * @interface ReviewPullRequestBody
 */
export interface ReviewPullRequestBody {
    /**
     * 
     * @type {ReviewDecision}
     * @memberof ReviewPullRequestBody
     */
    decision: ReviewDecision;
    /**
     * 
     * @type {string}
     * @memberof ReviewPullRequestBody
     */
    comment?: string;
}

/**
 * Check if a given object implements the ReviewPullRequestBody interface.
 */
export function instanceOfReviewPullRequestBody(value: object): boolean {
    if (!('decision' in value)) return false;
    return true;
}

export function ReviewPullRequestBodyFromJSON(json: any): ReviewPullRequestBody {
    return ReviewPullRequestBodyFromJSONTyped(json, false);
}

export function ReviewPullRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewPullRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'decision': ReviewDecisionFromJSON(json['decision']),
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function ReviewPullRequestBodyToJSON(value?: ReviewPullRequestBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'decision': ReviewDecisionToJSON(value['decision']),
        'comment': value['comment'],
    };
}

