/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';
import type { PullRequestDTO } from './PullRequestDTO';
import {
    PullRequestDTOFromJSON,
    PullRequestDTOFromJSONTyped,
    PullRequestDTOToJSON,
} from './PullRequestDTO';

/**
 * 
 * @export
 * @interface SearchPullRequestsBody
 */
export interface SearchPullRequestsBody {
    /**
     * 
     * @type {Array<PullRequestDTO>}
     * @memberof SearchPullRequestsBody
     */
    pullRequests: Array<PullRequestDTO>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof SearchPullRequestsBody
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the SearchPullRequestsBody interface.
 */
export function instanceOfSearchPullRequestsBody(value: object): boolean {
    if (!('pullRequests' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function SearchPullRequestsBodyFromJSON(json: any): SearchPullRequestsBody {
    return SearchPullRequestsBodyFromJSONTyped(json, false);
}

export function SearchPullRequestsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPullRequestsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'pullRequests': ((json['pullRequests'] as Array<any>).map(PullRequestDTOFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function SearchPullRequestsBodyToJSON(value?: SearchPullRequestsBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pullRequests': ((value['pullRequests'] as Array<any>).map(PullRequestDTOToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

