/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthorizedErrorResponseContent
 */
export interface UnauthorizedErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof UnauthorizedErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the UnauthorizedErrorResponseContent interface.
 */
export function instanceOfUnauthorizedErrorResponseContent(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function UnauthorizedErrorResponseContentFromJSON(json: any): UnauthorizedErrorResponseContent {
    return UnauthorizedErrorResponseContentFromJSONTyped(json, false);
}

export function UnauthorizedErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthorizedErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function UnauthorizedErrorResponseContentToJSON(value?: UnauthorizedErrorResponseContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

