/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnprocessableEntityErrorResponseContent
 */
export interface UnprocessableEntityErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof UnprocessableEntityErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the UnprocessableEntityErrorResponseContent interface.
 */
export function instanceOfUnprocessableEntityErrorResponseContent(value: object): boolean {
    if (!('message' in value)) return false;
    return true;
}

export function UnprocessableEntityErrorResponseContentFromJSON(json: any): UnprocessableEntityErrorResponseContent {
    return UnprocessableEntityErrorResponseContentFromJSONTyped(json, false);
}

export function UnprocessableEntityErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnprocessableEntityErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function UnprocessableEntityErrorResponseContentToJSON(value?: UnprocessableEntityErrorResponseContent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

