/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type BadRequestErrorResponseContent,
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
} from '../models/BadRequestErrorResponseContent';
import {
    type ConflictErrorResponseContent,
    ConflictErrorResponseContentFromJSON,
    ConflictErrorResponseContentToJSON,
} from '../models/ConflictErrorResponseContent';
import {
    type CreatePullRequestBody,
    CreatePullRequestBodyFromJSON,
    CreatePullRequestBodyToJSON,
} from '../models/CreatePullRequestBody';
import {
    type CreatePullRequestCommentBody,
    CreatePullRequestCommentBodyFromJSON,
    CreatePullRequestCommentBodyToJSON,
} from '../models/CreatePullRequestCommentBody';
import {
    type ForbiddenErrorResponseContent,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
} from '../models/ForbiddenErrorResponseContent';
import {
    type InternalServerErrorResponseContent,
    InternalServerErrorResponseContentFromJSON,
    InternalServerErrorResponseContentToJSON,
} from '../models/InternalServerErrorResponseContent';
import {
    type ListPullRequestCommentsBody,
    ListPullRequestCommentsBodyFromJSON,
    ListPullRequestCommentsBodyToJSON,
} from '../models/ListPullRequestCommentsBody';
import {
    type ListPullRequestsBody,
    ListPullRequestsBodyFromJSON,
    ListPullRequestsBodyToJSON,
} from '../models/ListPullRequestsBody';
import {
    type MergePullRequestBody,
    MergePullRequestBodyFromJSON,
    MergePullRequestBodyToJSON,
} from '../models/MergePullRequestBody';
import {
    type NotFoundErrorResponseContent,
    NotFoundErrorResponseContentFromJSON,
    NotFoundErrorResponseContentToJSON,
} from '../models/NotFoundErrorResponseContent';
import {
    type PrStatus,
    PrStatusFromJSON,
    PrStatusToJSON,
} from '../models/PrStatus';
import {
    type PullRequestCommentDTO,
    PullRequestCommentDTOFromJSON,
    PullRequestCommentDTOToJSON,
} from '../models/PullRequestCommentDTO';
import {
    type PullRequestDTO,
    PullRequestDTOFromJSON,
    PullRequestDTOToJSON,
} from '../models/PullRequestDTO';
import {
    type PullRequestMergeabilityDTO,
    PullRequestMergeabilityDTOFromJSON,
    PullRequestMergeabilityDTOToJSON,
} from '../models/PullRequestMergeabilityDTO';
import {
    type ReviewPullRequestBody,
    ReviewPullRequestBodyFromJSON,
    ReviewPullRequestBodyToJSON,
} from '../models/ReviewPullRequestBody';
import {
    type UnauthorizedErrorResponseContent,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
} from '../models/UnauthorizedErrorResponseContent';
import {
    type UnprocessableEntityErrorResponseContent,
    UnprocessableEntityErrorResponseContentFromJSON,
    UnprocessableEntityErrorResponseContentToJSON,
} from '../models/UnprocessableEntityErrorResponseContent';

export interface CreatePullRequestRequest {
    owner: string;
    repo: string;
    createPullRequestBody: CreatePullRequestBody;
}

export interface CreatePullRequestCommentRequest {
    owner: string;
    repo: string;
    prNumber: number;
    createPullRequestCommentBody: CreatePullRequestCommentBody;
}

export interface GetPullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface GetPullRequestMergeabilityRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface ListPullRequestCommentsRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface ListPullRequestsRequest {
    owner: string;
    repo: string;
    status?: PrStatus;
}

export interface MergePullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
    mergePullRequestBody: MergePullRequestBody;
}

export interface ReviewPullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
    reviewPullRequestBody: ReviewPullRequestBody;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Creates request options for createPullRequest without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {CreatePullRequestBody} createPullRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestRequestOpts(requestParameters: CreatePullRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Crea un pull request entre dos ramas. RF07.1
     * @param {string} owner 
     * @param {string} repo 
     * @param {CreatePullRequestBody} createPullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestRaw(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    createPullRequest(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Creates request options for createPullRequestComment without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {CreatePullRequestCommentBody} createPullRequestCommentBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestCommentRequestOpts(requestParameters: CreatePullRequestCommentRequest): Promise<runtime.RequestOpts>;

    /**
     * Agrega un comentario general o por linea a un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {CreatePullRequestCommentBody} createPullRequestCommentBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestCommentRaw(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestCommentDTO>>;

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    createPullRequestComment(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestCommentDTO>;

    /**
     * Creates request options for getPullRequest without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestRequestOpts(requestParameters: GetPullRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Obtiene el detalle de un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestRaw(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Obtiene el detalle de un pull request.
     */
    getPullRequest(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Creates request options for getPullRequestMergeability without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestMergeabilityRequestOpts(requestParameters: GetPullRequestMergeabilityRequest): Promise<runtime.RequestOpts>;

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestMergeabilityRaw(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestMergeabilityDTO>>;

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    getPullRequestMergeability(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestMergeabilityDTO>;

    /**
     * Creates request options for listPullRequestComments without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestCommentsRequestOpts(requestParameters: ListPullRequestCommentsRequest): Promise<runtime.RequestOpts>;

    /**
     * Lista comentarios de un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestCommentsRaw(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestCommentsBody>>;

    /**
     * Lista comentarios de un pull request.
     */
    listPullRequestComments(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestCommentsBody>;

    /**
     * Creates request options for listPullRequests without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {PrStatus} [status] 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestsRequestOpts(requestParameters: ListPullRequestsRequest): Promise<runtime.RequestOpts>;

    /**
     * Lista los pull requests del repositorio. RF07
     * @param {string} owner 
     * @param {string} repo 
     * @param {PrStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestsRaw(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestsBody>>;

    /**
     * Lista los pull requests del repositorio. RF07
     */
    listPullRequests(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestsBody>;

    /**
     * Creates request options for mergePullRequest without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {MergePullRequestBody} mergePullRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    mergePullRequestRequestOpts(requestParameters: MergePullRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {MergePullRequestBody} mergePullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    mergePullRequestRaw(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    mergePullRequest(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Creates request options for reviewPullRequest without sending the request
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {ReviewPullRequestBody} reviewPullRequestBody 
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    reviewPullRequestRequestOpts(requestParameters: ReviewPullRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {ReviewPullRequestBody} reviewPullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    reviewPullRequestRaw(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    reviewPullRequest(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Creates request options for createPullRequest without sending the request
     */
    async createPullRequestRequestOpts(requestParameters: CreatePullRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['createPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestBody',
                'Required parameter "createPullRequestBody" was null or undefined when calling createPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestBodyToJSON(requestParameters['createPullRequestBody']),
        };
    }

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    async createPullRequestRaw(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        const requestOptions = await this.createPullRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    async createPullRequest(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.createPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPullRequestComment without sending the request
     */
    async createPullRequestCommentRequestOpts(requestParameters: CreatePullRequestCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['createPullRequestCommentBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestCommentBody',
                'Required parameter "createPullRequestCommentBody" was null or undefined when calling createPullRequestComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestCommentBodyToJSON(requestParameters['createPullRequestCommentBody']),
        };
    }

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    async createPullRequestCommentRaw(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestCommentDTO>> {
        const requestOptions = await this.createPullRequestCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestCommentDTOFromJSON(jsonValue));
    }

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    async createPullRequestComment(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestCommentDTO> {
        const response = await this.createPullRequestCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPullRequest without sending the request
     */
    async getPullRequestRequestOpts(requestParameters: GetPullRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling getPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtiene el detalle de un pull request.
     */
    async getPullRequestRaw(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        const requestOptions = await this.getPullRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Obtiene el detalle de un pull request.
     */
    async getPullRequest(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.getPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPullRequestMergeability without sending the request
     */
    async getPullRequestMergeabilityRequestOpts(requestParameters: GetPullRequestMergeabilityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}/mergeability`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    async getPullRequestMergeabilityRaw(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestMergeabilityDTO>> {
        const requestOptions = await this.getPullRequestMergeabilityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestMergeabilityDTOFromJSON(jsonValue));
    }

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    async getPullRequestMergeability(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestMergeabilityDTO> {
        const response = await this.getPullRequestMergeabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPullRequestComments without sending the request
     */
    async listPullRequestCommentsRequestOpts(requestParameters: ListPullRequestCommentsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling listPullRequestComments().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling listPullRequestComments().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling listPullRequestComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista comentarios de un pull request.
     */
    async listPullRequestCommentsRaw(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestCommentsBody>> {
        const requestOptions = await this.listPullRequestCommentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPullRequestCommentsBodyFromJSON(jsonValue));
    }

    /**
     * Lista comentarios de un pull request.
     */
    async listPullRequestComments(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestCommentsBody> {
        const response = await this.listPullRequestCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPullRequests without sending the request
     */
    async listPullRequestsRequestOpts(requestParameters: ListPullRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling listPullRequests().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling listPullRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lista los pull requests del repositorio. RF07
     */
    async listPullRequestsRaw(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestsBody>> {
        const requestOptions = await this.listPullRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPullRequestsBodyFromJSON(jsonValue));
    }

    /**
     * Lista los pull requests del repositorio. RF07
     */
    async listPullRequests(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestsBody> {
        const response = await this.listPullRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mergePullRequest without sending the request
     */
    async mergePullRequestRequestOpts(requestParameters: MergePullRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['mergePullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'mergePullRequestBody',
                'Required parameter "mergePullRequestBody" was null or undefined when calling mergePullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}/merge`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MergePullRequestBodyToJSON(requestParameters['mergePullRequestBody']),
        };
    }

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    async mergePullRequestRaw(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        const requestOptions = await this.mergePullRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    async mergePullRequest(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.mergePullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reviewPullRequest without sending the request
     */
    async reviewPullRequestRequestOpts(requestParameters: ReviewPullRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['reviewPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'reviewPullRequestBody',
                'Required parameter "reviewPullRequestBody" was null or undefined when calling reviewPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/repos/{owner}/{repo}/pulls/{prNumber}/review`;
        urlPath = urlPath.replace('{owner}', encodeURIComponent(String(requestParameters['owner'])));
        urlPath = urlPath.replace('{repo}', encodeURIComponent(String(requestParameters['repo'])));
        urlPath = urlPath.replace('{prNumber}', encodeURIComponent(String(requestParameters['prNumber'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewPullRequestBodyToJSON(requestParameters['reviewPullRequestBody']),
        };
    }

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    async reviewPullRequestRaw(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        const requestOptions = await this.reviewPullRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    async reviewPullRequest(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.reviewPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
