/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestErrorResponseContent,
  CompareDTO,
  ConflictErrorResponseContent,
  CreateFileBody,
  CreateFolderBody,
  DeleteFileResponseBody,
  FileOperationResponse,
  ForbiddenErrorResponseContent,
  GetCommitBody,
  GetFileContentBody,
  InternalServerErrorResponseContent,
  ListCommitsBody,
  NotFoundErrorResponseContent,
  UnauthorizedErrorResponseContent,
  UpdateFileBody,
} from '../models/index';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    CompareDTOFromJSON,
    CompareDTOToJSON,
    ConflictErrorResponseContentFromJSON,
    ConflictErrorResponseContentToJSON,
    CreateFileBodyFromJSON,
    CreateFileBodyToJSON,
    CreateFolderBodyFromJSON,
    CreateFolderBodyToJSON,
    DeleteFileResponseBodyFromJSON,
    DeleteFileResponseBodyToJSON,
    FileOperationResponseFromJSON,
    FileOperationResponseToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    GetCommitBodyFromJSON,
    GetCommitBodyToJSON,
    GetFileContentBodyFromJSON,
    GetFileContentBodyToJSON,
    InternalServerErrorResponseContentFromJSON,
    InternalServerErrorResponseContentToJSON,
    ListCommitsBodyFromJSON,
    ListCommitsBodyToJSON,
    NotFoundErrorResponseContentFromJSON,
    NotFoundErrorResponseContentToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    UpdateFileBodyFromJSON,
    UpdateFileBodyToJSON,
} from '../models/index';

export interface CompareCommitsRequest {
    owner: string;
    repo: string;
    baseBranch: string;
    headBranch: string;
}

export interface CreateFileRequest {
    owner: string;
    repo: string;
    filePath: string;
    createFileBody: CreateFileBody;
}

export interface CreateFolderRequest {
    owner: string;
    repo: string;
    createFolderBody: CreateFolderBody;
}

export interface DeleteFileRequest {
    owner: string;
    repo: string;
    filePath: string;
    sha: string;
    message: string;
    branch?: string;
}

export interface GetCommitRequest {
    owner: string;
    repo: string;
    sha: string;
}

export interface GetCommitDiffRequest {
    owner: string;
    repo: string;
    sha: string;
}

export interface GetFileContentRequest {
    owner: string;
    repo: string;
    filePath: string;
    ref?: string;
}

export interface GetRawFileRequest {
    owner: string;
    repo: string;
    path: string;
    ref?: string;
}

export interface GetRepositoryContentsRequest {
    owner: string;
    repo: string;
    path?: string;
    ref?: string;
}

export interface ListCommitsRequest {
    owner: string;
    repo: string;
    sha?: string;
    path?: string;
    page?: number;
    perPage?: number;
}

export interface UpdateFileRequest {
    owner: string;
    repo: string;
    filePath: string;
    updateFileBody: UpdateFileBody;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Compara dos branches mostrando commits y archivos cambiados. HU-20
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} baseBranch Branch base para comparacion
     * @param {string} headBranch Branch head para comparacion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    compareCommitsRaw(requestParameters: CompareCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompareDTO>>;

    /**
     * Compara dos branches mostrando commits y archivos cambiados. HU-20
     */
    compareCommits(requestParameters: CompareCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompareDTO>;

    /**
     * Sube un archivo al repositorio (create/update por path). RF03.1
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} filePath 
     * @param {CreateFileBody} createFileBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createFileRaw(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>>;

    /**
     * Sube un archivo al repositorio (create/update por path). RF03.1
     */
    createFile(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse>;

    /**
     * Crea una carpeta nueva con .gitkeep. RF03.4
     * @param {string} owner 
     * @param {string} repo 
     * @param {CreateFolderBody} createFolderBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createFolderRaw(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>>;

    /**
     * Crea una carpeta nueva con .gitkeep. RF03.4
     */
    createFolder(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse>;

    /**
     * Elimina un archivo generando un commit de borrado. RF03.5
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} filePath 
     * @param {string} sha SHA del archivo a eliminar (para control de concurrencia)
     * @param {string} message Mensaje del commit
     * @param {string} [branch] Branch donde eliminar
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteFileResponseBody>>;

    /**
     * Elimina un archivo generando un commit de borrado. RF03.5
     */
    deleteFile(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteFileResponseBody>;

    /**
     * Obtiene el detalle de un commit especifico. HU-18
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} sha 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommitRaw(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCommitBody>>;

    /**
     * Obtiene el detalle de un commit especifico. HU-18
     */
    getCommit(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCommitBody>;

    /**
     * Obtiene el diff de un commit en formato texto. HU-18
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} sha 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getCommitDiffRaw(requestParameters: GetCommitDiffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Obtiene el diff de un commit en formato texto. HU-18
     */
    getCommitDiff(requestParameters: GetCommitDiffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} filePath 
     * @param {string} [ref] Branch, tag o commit SHA
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getFileContentRaw(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFileContentBody>>;

    /**
     * Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3
     */
    getFileContent(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFileContentBody>;

    /**
     * Descarga un archivo individual del repositorio. RF03.2
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} path 
     * @param {string} [ref] Branch, tag o commit SHA
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRawFileRaw(requestParameters: GetRawFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Descarga un archivo individual del repositorio. RF03.2
     */
    getRawFile(requestParameters: GetRawFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Lista el contenido de una ruta del repositorio usando query path. HU-13
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} [path] Ruta relativa opcional. Si se omite, lista la raiz.
     * @param {string} [ref] Branch, tag o commit SHA
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getRepositoryContentsRaw(requestParameters: GetRepositoryContentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFileContentBody>>;

    /**
     * Lista el contenido de una ruta del repositorio usando query path. HU-13
     */
    getRepositoryContents(requestParameters: GetRepositoryContentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFileContentBody>;

    /**
     * Lista el historial de commits del repositorio. HU-18
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} [sha] Branch o SHA desde donde empezar
     * @param {string} [path] Filtrar por path de archivo
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listCommitsRaw(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCommitsBody>>;

    /**
     * Lista el historial de commits del repositorio. HU-18
     */
    listCommits(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCommitsBody>;

    /**
     * Actualiza un archivo existente en el repositorio. RF03.1
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} filePath 
     * @param {UpdateFileBody} updateFileBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    updateFileRaw(requestParameters: UpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>>;

    /**
     * Actualiza un archivo existente en el repositorio. RF03.1
     */
    updateFile(requestParameters: UpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Compara dos branches mostrando commits y archivos cambiados. HU-20
     */
    async compareCommitsRaw(requestParameters: CompareCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompareDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling compareCommits().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling compareCommits().'
            );
        }

        if (requestParameters['baseBranch'] == null) {
            throw new runtime.RequiredError(
                'baseBranch',
                'Required parameter "baseBranch" was null or undefined when calling compareCommits().'
            );
        }

        if (requestParameters['headBranch'] == null) {
            throw new runtime.RequiredError(
                'headBranch',
                'Required parameter "headBranch" was null or undefined when calling compareCommits().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/compare/{baseBranch}/{headBranch}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"baseBranch"}}`, encodeURIComponent(String(requestParameters['baseBranch']))).replace(`{${"headBranch"}}`, encodeURIComponent(String(requestParameters['headBranch']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompareDTOFromJSON(jsonValue));
    }

    /**
     * Compara dos branches mostrando commits y archivos cambiados. HU-20
     */
    async compareCommits(requestParameters: CompareCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompareDTO> {
        const response = await this.compareCommitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sube un archivo al repositorio (create/update por path). RF03.1
     */
    async createFileRaw(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createFile().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createFile().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling createFile().'
            );
        }

        if (requestParameters['createFileBody'] == null) {
            throw new runtime.RequiredError(
                'createFileBody',
                'Required parameter "createFileBody" was null or undefined when calling createFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/contents/{filePath+}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"filePath+"}}`, encodeURIComponent(String(requestParameters['filePath']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFileBodyToJSON(requestParameters['createFileBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOperationResponseFromJSON(jsonValue));
    }

    /**
     * Sube un archivo al repositorio (create/update por path). RF03.1
     */
    async createFile(requestParameters: CreateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse> {
        const response = await this.createFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Crea una carpeta nueva con .gitkeep. RF03.4
     */
    async createFolderRaw(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createFolder().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createFolder().'
            );
        }

        if (requestParameters['createFolderBody'] == null) {
            throw new runtime.RequiredError(
                'createFolderBody',
                'Required parameter "createFolderBody" was null or undefined when calling createFolder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/folders`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFolderBodyToJSON(requestParameters['createFolderBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOperationResponseFromJSON(jsonValue));
    }

    /**
     * Crea una carpeta nueva con .gitkeep. RF03.4
     */
    async createFolder(requestParameters: CreateFolderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse> {
        const response = await this.createFolderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Elimina un archivo generando un commit de borrado. RF03.5
     */
    async deleteFileRaw(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteFileResponseBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['sha'] == null) {
            throw new runtime.RequiredError(
                'sha',
                'Required parameter "sha" was null or undefined when calling deleteFile().'
            );
        }

        if (requestParameters['message'] == null) {
            throw new runtime.RequiredError(
                'message',
                'Required parameter "message" was null or undefined when calling deleteFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sha'] != null) {
            queryParameters['sha'] = requestParameters['sha'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/contents/{filePath+}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"filePath+"}}`, encodeURIComponent(String(requestParameters['filePath']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteFileResponseBodyFromJSON(jsonValue));
    }

    /**
     * Elimina un archivo generando un commit de borrado. RF03.5
     */
    async deleteFile(requestParameters: DeleteFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteFileResponseBody> {
        const response = await this.deleteFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Obtiene el detalle de un commit especifico. HU-18
     */
    async getCommitRaw(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCommitBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getCommit().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getCommit().'
            );
        }

        if (requestParameters['sha'] == null) {
            throw new runtime.RequiredError(
                'sha',
                'Required parameter "sha" was null or undefined when calling getCommit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/commits/{sha}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"sha"}}`, encodeURIComponent(String(requestParameters['sha']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCommitBodyFromJSON(jsonValue));
    }

    /**
     * Obtiene el detalle de un commit especifico. HU-18
     */
    async getCommit(requestParameters: GetCommitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCommitBody> {
        const response = await this.getCommitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Obtiene el diff de un commit en formato texto. HU-18
     */
    async getCommitDiffRaw(requestParameters: GetCommitDiffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getCommitDiff().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getCommitDiff().'
            );
        }

        if (requestParameters['sha'] == null) {
            throw new runtime.RequiredError(
                'sha',
                'Required parameter "sha" was null or undefined when calling getCommitDiff().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/commits/{sha}/diff`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"sha"}}`, encodeURIComponent(String(requestParameters['sha']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Obtiene el diff de un commit en formato texto. HU-18
     */
    async getCommitDiff(requestParameters: GetCommitDiffRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getCommitDiffRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3
     */
    async getFileContentRaw(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFileContentBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getFileContent().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getFileContent().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling getFileContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ref'] != null) {
            queryParameters['ref'] = requestParameters['ref'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/contents/{filePath+}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"filePath+"}}`, encodeURIComponent(String(requestParameters['filePath']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetFileContentBodyFromJSON(jsonValue));
    }

    /**
     * Obtiene el contenido de un archivo o lista el contenido de un directorio. RF03.3
     */
    async getFileContent(requestParameters: GetFileContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFileContentBody> {
        const response = await this.getFileContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Descarga un archivo individual del repositorio. RF03.2
     */
    async getRawFileRaw(requestParameters: GetRawFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getRawFile().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getRawFile().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getRawFile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['ref'] != null) {
            queryParameters['ref'] = requestParameters['ref'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/download`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Descarga un archivo individual del repositorio. RF03.2
     */
    async getRawFile(requestParameters: GetRawFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getRawFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lista el contenido de una ruta del repositorio usando query path. HU-13
     */
    async getRepositoryContentsRaw(requestParameters: GetRepositoryContentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetFileContentBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getRepositoryContents().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getRepositoryContents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['ref'] != null) {
            queryParameters['ref'] = requestParameters['ref'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/contents`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetFileContentBodyFromJSON(jsonValue));
    }

    /**
     * Lista el contenido de una ruta del repositorio usando query path. HU-13
     */
    async getRepositoryContents(requestParameters: GetRepositoryContentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetFileContentBody> {
        const response = await this.getRepositoryContentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lista el historial de commits del repositorio. HU-18
     */
    async listCommitsRaw(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCommitsBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling listCommits().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling listCommits().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sha'] != null) {
            queryParameters['sha'] = requestParameters['sha'];
        }

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/commits`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCommitsBodyFromJSON(jsonValue));
    }

    /**
     * Lista el historial de commits del repositorio. HU-18
     */
    async listCommits(requestParameters: ListCommitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCommitsBody> {
        const response = await this.listCommitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Actualiza un archivo existente en el repositorio. RF03.1
     */
    async updateFileRaw(requestParameters: UpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileOperationResponse>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling updateFile().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling updateFile().'
            );
        }

        if (requestParameters['filePath'] == null) {
            throw new runtime.RequiredError(
                'filePath',
                'Required parameter "filePath" was null or undefined when calling updateFile().'
            );
        }

        if (requestParameters['updateFileBody'] == null) {
            throw new runtime.RequiredError(
                'updateFileBody',
                'Required parameter "updateFileBody" was null or undefined when calling updateFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/contents/{filePath+}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"filePath+"}}`, encodeURIComponent(String(requestParameters['filePath']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFileBodyToJSON(requestParameters['updateFileBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileOperationResponseFromJSON(jsonValue));
    }

    /**
     * Actualiza un archivo existente en el repositorio. RF03.1
     */
    async updateFile(requestParameters: UpdateFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileOperationResponse> {
        const response = await this.updateFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
