/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Composites
 */
export interface Composites {
    /**
     * 
     * @type {Set<string>}
     * @memberof Composites
     */
    realm?: Set<string>;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Composites
     */
    client?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof Composites
     * @deprecated
     */
    application?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the Composites interface.
 */
export function instanceOfComposites(value: object): value is Composites {
    return true;
}

export function CompositesFromJSON(json: any): Composites {
    return CompositesFromJSONTyped(json, false);
}

export function CompositesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Composites {
    if (json == null) {
        return json;
    }
    return {
        
        'realm': json['realm'] == null ? undefined : new Set(json['realm']),
        'client': json['client'] == null ? undefined : json['client'],
        'application': json['application'] == null ? undefined : json['application'],
    };
}

export function CompositesToJSON(json: any): Composites {
    return CompositesToJSONTyped(json, false);
}

export function CompositesToJSONTyped(value?: Composites | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'realm': value['realm'] == null ? undefined : Array.from(value['realm'] as Set<any>),
        'client': value['client'],
        'application': value['application'],
    };
}

