/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FilterRequest
 */
export interface FilterRequest {
    /**
     * 
     * @type {string}
     * @memberof FilterRequest
     */
    key?: string;
    /**
     * 
     * @type {FilterRequestOperatorEnum}
     * @memberof FilterRequest
     */
    operator?: FilterRequestOperatorEnum;
    /**
     * 
     * @type {FilterRequestFieldTypeEnum}
     * @memberof FilterRequest
     */
    fieldType?: FilterRequestFieldTypeEnum;
    /**
     * 
     * @type {any}
     * @memberof FilterRequest
     */
    value?: any | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof FilterRequest
     */
    values?: Array<any>;
    /**
     * 
     * @type {any}
     * @memberof FilterRequest
     */
    valueTo?: any | null;
}


/**
 * @export
 */
export const FilterRequestOperatorEnum = {
    Equal: 'EQUAL',
    NotEqual: 'NOT_EQUAL',
    Like: 'LIKE',
    In: 'IN',
    Between: 'BETWEEN',
    LessThan: 'LESS_THAN'
} as const;
export type FilterRequestOperatorEnum = typeof FilterRequestOperatorEnum[keyof typeof FilterRequestOperatorEnum];

/**
 * @export
 */
export const FilterRequestFieldTypeEnum = {
    Boolean: 'BOOLEAN',
    Char: 'CHAR',
    Date: 'DATE',
    Double: 'DOUBLE',
    Integer: 'INTEGER',
    Long: 'LONG',
    String: 'STRING'
} as const;
export type FilterRequestFieldTypeEnum = typeof FilterRequestFieldTypeEnum[keyof typeof FilterRequestFieldTypeEnum];


/**
 * Check if a given object implements the FilterRequest interface.
 */
export function instanceOfFilterRequest(value: object): value is FilterRequest {
    return true;
}

export function FilterRequestFromJSON(json: any): FilterRequest {
    return FilterRequestFromJSONTyped(json, false);
}

export function FilterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'fieldType': json['fieldType'] == null ? undefined : json['fieldType'],
        'value': json['value'] == null ? undefined : json['value'],
        'values': json['values'] == null ? undefined : json['values'],
        'valueTo': json['valueTo'] == null ? undefined : json['valueTo'],
    };
}

export function FilterRequestToJSON(json: any): FilterRequest {
    return FilterRequestToJSONTyped(json, false);
}

export function FilterRequestToJSONTyped(value?: FilterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'operator': value['operator'],
        'fieldType': value['fieldType'],
        'value': value['value'],
        'values': value['values'],
        'valueTo': value['valueTo'],
    };
}

