/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageUserResponse
 */
export interface PageUserResponse {
    /**
     * 
     * @type {number}
     * @memberof PageUserResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof PageUserResponse
     */
    content?: Array<UserResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageUserResponse
     */
    number?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserResponse
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageUserResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageUserResponse
     */
    sort?: SortObject;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageUserResponse
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageUserResponse interface.
 */
export function instanceOfPageUserResponse(value: object): value is PageUserResponse {
    return true;
}

export function PageUserResponseFromJSON(json: any): PageUserResponse {
    return PageUserResponseFromJSONTyped(json, false);
}

export function PageUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageUserResponseToJSON(json: any): PageUserResponse {
    return PageUserResponseToJSONTyped(json, false);
}

export function PageUserResponseToJSONTyped(value?: PageUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserResponseToJSON)),
        'number': value['number'],
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'sort': SortObjectToJSON(value['sort']),
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

