/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScopeRepresentation } from './ScopeRepresentation';
import {
    ScopeRepresentationFromJSON,
    ScopeRepresentationFromJSONTyped,
    ScopeRepresentationToJSON,
    ScopeRepresentationToJSONTyped,
} from './ScopeRepresentation';
import type { ResourceRepresentation } from './ResourceRepresentation';
import {
    ResourceRepresentationFromJSON,
    ResourceRepresentationFromJSONTyped,
    ResourceRepresentationToJSON,
    ResourceRepresentationToJSONTyped,
} from './ResourceRepresentation';

/**
 * 
 * @export
 * @interface PolicyRepresentation
 */
export interface PolicyRepresentation {
    /**
     * 
     * @type {string}
     * @memberof PolicyRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyRepresentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyRepresentation
     */
    type?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof PolicyRepresentation
     */
    policies?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof PolicyRepresentation
     */
    resources?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof PolicyRepresentation
     */
    scopes?: Set<string>;
    /**
     * 
     * @type {PolicyRepresentationLogicEnum}
     * @memberof PolicyRepresentation
     */
    logic?: PolicyRepresentationLogicEnum;
    /**
     * 
     * @type {PolicyRepresentationDecisionStrategyEnum}
     * @memberof PolicyRepresentation
     */
    decisionStrategy?: PolicyRepresentationDecisionStrategyEnum;
    /**
     * 
     * @type {string}
     * @memberof PolicyRepresentation
     */
    owner?: string;
    /**
     * 
     * @type {Set<ResourceRepresentation>}
     * @memberof PolicyRepresentation
     */
    resourcesData?: Set<ResourceRepresentation>;
    /**
     * 
     * @type {Set<ScopeRepresentation>}
     * @memberof PolicyRepresentation
     */
    scopesData?: Set<ScopeRepresentation>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PolicyRepresentation
     */
    config?: { [key: string]: string; };
}


/**
 * @export
 */
export const PolicyRepresentationLogicEnum = {
    Positive: 'POSITIVE',
    Negative: 'NEGATIVE'
} as const;
export type PolicyRepresentationLogicEnum = typeof PolicyRepresentationLogicEnum[keyof typeof PolicyRepresentationLogicEnum];

/**
 * @export
 */
export const PolicyRepresentationDecisionStrategyEnum = {
    Affirmative: 'AFFIRMATIVE',
    Unanimous: 'UNANIMOUS',
    Consensus: 'CONSENSUS'
} as const;
export type PolicyRepresentationDecisionStrategyEnum = typeof PolicyRepresentationDecisionStrategyEnum[keyof typeof PolicyRepresentationDecisionStrategyEnum];


/**
 * Check if a given object implements the PolicyRepresentation interface.
 */
export function instanceOfPolicyRepresentation(value: object): value is PolicyRepresentation {
    return true;
}

export function PolicyRepresentationFromJSON(json: any): PolicyRepresentation {
    return PolicyRepresentationFromJSONTyped(json, false);
}

export function PolicyRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'policies': json['policies'] == null ? undefined : new Set(json['policies']),
        'resources': json['resources'] == null ? undefined : new Set(json['resources']),
        'scopes': json['scopes'] == null ? undefined : new Set(json['scopes']),
        'logic': json['logic'] == null ? undefined : json['logic'],
        'decisionStrategy': json['decisionStrategy'] == null ? undefined : json['decisionStrategy'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'resourcesData': json['resourcesData'] == null ? undefined : (new Set((json['resourcesData'] as Array<any>).map(ResourceRepresentationFromJSON))),
        'scopesData': json['scopesData'] == null ? undefined : (new Set((json['scopesData'] as Array<any>).map(ScopeRepresentationFromJSON))),
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function PolicyRepresentationToJSON(json: any): PolicyRepresentation {
    return PolicyRepresentationToJSONTyped(json, false);
}

export function PolicyRepresentationToJSONTyped(value?: PolicyRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'policies': value['policies'] == null ? undefined : Array.from(value['policies'] as Set<any>),
        'resources': value['resources'] == null ? undefined : Array.from(value['resources'] as Set<any>),
        'scopes': value['scopes'] == null ? undefined : Array.from(value['scopes'] as Set<any>),
        'logic': value['logic'],
        'decisionStrategy': value['decisionStrategy'],
        'owner': value['owner'],
        'resourcesData': value['resourcesData'] == null ? undefined : (Array.from(value['resourcesData'] as Set<any>).map(ResourceRepresentationToJSON)),
        'scopesData': value['scopesData'] == null ? undefined : (Array.from(value['scopesData'] as Set<any>).map(ScopeRepresentationToJSON)),
        'config': value['config'],
    };
}

