/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolicyRepresentation } from './PolicyRepresentation';
import {
    PolicyRepresentationFromJSON,
    PolicyRepresentationFromJSONTyped,
    PolicyRepresentationToJSON,
    PolicyRepresentationToJSONTyped,
} from './PolicyRepresentation';
import type { ScopeRepresentation } from './ScopeRepresentation';
import {
    ScopeRepresentationFromJSON,
    ScopeRepresentationFromJSONTyped,
    ScopeRepresentationToJSON,
    ScopeRepresentationToJSONTyped,
} from './ScopeRepresentation';
import type { ResourceRepresentation } from './ResourceRepresentation';
import {
    ResourceRepresentationFromJSON,
    ResourceRepresentationFromJSONTyped,
    ResourceRepresentationToJSON,
    ResourceRepresentationToJSONTyped,
} from './ResourceRepresentation';

/**
 * 
 * @export
 * @interface ResourceServerRepresentation
 */
export interface ResourceServerRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceServerRepresentation
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceServerRepresentation
     */
    allowRemoteResourceManagement?: boolean;
    /**
     * 
     * @type {ResourceServerRepresentationPolicyEnforcementModeEnum}
     * @memberof ResourceServerRepresentation
     */
    policyEnforcementMode?: ResourceServerRepresentationPolicyEnforcementModeEnum;
    /**
     * 
     * @type {Array<ResourceRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    resources?: Array<ResourceRepresentation>;
    /**
     * 
     * @type {Array<PolicyRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    policies?: Array<PolicyRepresentation>;
    /**
     * 
     * @type {Array<ScopeRepresentation>}
     * @memberof ResourceServerRepresentation
     */
    scopes?: Array<ScopeRepresentation>;
    /**
     * 
     * @type {ResourceServerRepresentationDecisionStrategyEnum}
     * @memberof ResourceServerRepresentation
     */
    decisionStrategy?: ResourceServerRepresentationDecisionStrategyEnum;
}


/**
 * @export
 */
export const ResourceServerRepresentationPolicyEnforcementModeEnum = {
    Enforcing: 'ENFORCING',
    Permissive: 'PERMISSIVE',
    Disabled: 'DISABLED'
} as const;
export type ResourceServerRepresentationPolicyEnforcementModeEnum = typeof ResourceServerRepresentationPolicyEnforcementModeEnum[keyof typeof ResourceServerRepresentationPolicyEnforcementModeEnum];

/**
 * @export
 */
export const ResourceServerRepresentationDecisionStrategyEnum = {
    Affirmative: 'AFFIRMATIVE',
    Unanimous: 'UNANIMOUS',
    Consensus: 'CONSENSUS'
} as const;
export type ResourceServerRepresentationDecisionStrategyEnum = typeof ResourceServerRepresentationDecisionStrategyEnum[keyof typeof ResourceServerRepresentationDecisionStrategyEnum];


/**
 * Check if a given object implements the ResourceServerRepresentation interface.
 */
export function instanceOfResourceServerRepresentation(value: object): value is ResourceServerRepresentation {
    return true;
}

export function ResourceServerRepresentationFromJSON(json: any): ResourceServerRepresentation {
    return ResourceServerRepresentationFromJSONTyped(json, false);
}

export function ResourceServerRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceServerRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'name': json['name'] == null ? undefined : json['name'],
        'allowRemoteResourceManagement': json['allowRemoteResourceManagement'] == null ? undefined : json['allowRemoteResourceManagement'],
        'policyEnforcementMode': json['policyEnforcementMode'] == null ? undefined : json['policyEnforcementMode'],
        'resources': json['resources'] == null ? undefined : ((json['resources'] as Array<any>).map(ResourceRepresentationFromJSON)),
        'policies': json['policies'] == null ? undefined : ((json['policies'] as Array<any>).map(PolicyRepresentationFromJSON)),
        'scopes': json['scopes'] == null ? undefined : ((json['scopes'] as Array<any>).map(ScopeRepresentationFromJSON)),
        'decisionStrategy': json['decisionStrategy'] == null ? undefined : json['decisionStrategy'],
    };
}

export function ResourceServerRepresentationToJSON(json: any): ResourceServerRepresentation {
    return ResourceServerRepresentationToJSONTyped(json, false);
}

export function ResourceServerRepresentationToJSONTyped(value?: ResourceServerRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'clientId': value['clientId'],
        'name': value['name'],
        'allowRemoteResourceManagement': value['allowRemoteResourceManagement'],
        'policyEnforcementMode': value['policyEnforcementMode'],
        'resources': value['resources'] == null ? undefined : ((value['resources'] as Array<any>).map(ResourceRepresentationToJSON)),
        'policies': value['policies'] == null ? undefined : ((value['policies'] as Array<any>).map(PolicyRepresentationToJSON)),
        'scopes': value['scopes'] == null ? undefined : ((value['scopes'] as Array<any>).map(ScopeRepresentationToJSON)),
        'decisionStrategy': value['decisionStrategy'],
    };
}

