/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScopeRepresentation } from './ScopeRepresentation';
import {
    ScopeRepresentationFromJSON,
    ScopeRepresentationFromJSONTyped,
    ScopeRepresentationToJSON,
    ScopeRepresentationToJSONTyped,
} from './ScopeRepresentation';
import type { ResourceOwnerRepresentation } from './ResourceOwnerRepresentation';
import {
    ResourceOwnerRepresentationFromJSON,
    ResourceOwnerRepresentationFromJSONTyped,
    ResourceOwnerRepresentationToJSON,
    ResourceOwnerRepresentationToJSONTyped,
} from './ResourceOwnerRepresentation';

/**
 * 
 * @export
 * @interface ResourceRepresentation
 */
export interface ResourceRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     */
    type?: string;
    /**
     * 
     * @type {ResourceOwnerRepresentation}
     * @memberof ResourceRepresentation
     */
    owner?: ResourceOwnerRepresentation;
    /**
     * 
     * @type {boolean}
     * @memberof ResourceRepresentation
     */
    ownerManagedAccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     */
    displayName?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ResourceRepresentation
     */
    attributes?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     */
    id?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof ResourceRepresentation
     */
    uris?: Set<string>;
    /**
     * 
     * @type {Set<ScopeRepresentation>}
     * @memberof ResourceRepresentation
     */
    scopes?: Set<ScopeRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     */
    iconUri?: string;
    /**
     * 
     * @type {Set<ScopeRepresentation>}
     * @memberof ResourceRepresentation
     */
    resourceScopes?: Set<ScopeRepresentation>;
    /**
     * 
     * @type {string}
     * @memberof ResourceRepresentation
     * @deprecated
     */
    uri?: string;
}

/**
 * Check if a given object implements the ResourceRepresentation interface.
 */
export function instanceOfResourceRepresentation(value: object): value is ResourceRepresentation {
    return true;
}

export function ResourceRepresentationFromJSON(json: any): ResourceRepresentation {
    return ResourceRepresentationFromJSONTyped(json, false);
}

export function ResourceRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'owner': json['owner'] == null ? undefined : ResourceOwnerRepresentationFromJSON(json['owner']),
        'ownerManagedAccess': json['ownerManagedAccess'] == null ? undefined : json['ownerManagedAccess'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'id': json['_id'] == null ? undefined : json['_id'],
        'uris': json['uris'] == null ? undefined : new Set(json['uris']),
        'scopes': json['scopes'] == null ? undefined : (new Set((json['scopes'] as Array<any>).map(ScopeRepresentationFromJSON))),
        'iconUri': json['icon_uri'] == null ? undefined : json['icon_uri'],
        'resourceScopes': json['resource_scopes'] == null ? undefined : (new Set((json['resource_scopes'] as Array<any>).map(ScopeRepresentationFromJSON))),
        'uri': json['uri'] == null ? undefined : json['uri'],
    };
}

export function ResourceRepresentationToJSON(json: any): ResourceRepresentation {
    return ResourceRepresentationToJSONTyped(json, false);
}

export function ResourceRepresentationToJSONTyped(value?: ResourceRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'owner': ResourceOwnerRepresentationToJSON(value['owner']),
        'ownerManagedAccess': value['ownerManagedAccess'],
        'displayName': value['displayName'],
        'attributes': value['attributes'],
        '_id': value['id'],
        'uris': value['uris'] == null ? undefined : Array.from(value['uris'] as Set<any>),
        'scopes': value['scopes'] == null ? undefined : (Array.from(value['scopes'] as Set<any>).map(ScopeRepresentationToJSON)),
        'icon_uri': value['iconUri'],
        'resource_scopes': value['resourceScopes'] == null ? undefined : (Array.from(value['resourceScopes'] as Set<any>).map(ScopeRepresentationToJSON)),
        'uri': value['uri'],
    };
}

