/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceOwnerRepresentation
 */
export interface ResourceOwnerRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ResourceOwnerRepresentation
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceOwnerRepresentation
     */
    name?: string;
}

/**
 * Check if a given object implements the ResourceOwnerRepresentation interface.
 */
export function instanceOfResourceOwnerRepresentation(value: object): value is ResourceOwnerRepresentation {
    return true;
}

export function ResourceOwnerRepresentationFromJSON(json: any): ResourceOwnerRepresentation {
    return ResourceOwnerRepresentationFromJSONTyped(json, false);
}

export function ResourceOwnerRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceOwnerRepresentation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ResourceOwnerRepresentationToJSON(json: any): ResourceOwnerRepresentation {
    return ResourceOwnerRepresentationToJSONTyped(json, false);
}

export function ResourceOwnerRepresentationToJSONTyped(value?: ResourceOwnerRepresentation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

