/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RolLinkRequest
 */
export interface RolLinkRequest {
    /**
     * 
     * @type {string}
     * @memberof RolLinkRequest
     */
    rolId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RolLinkRequest
     */
    vincular?: boolean;
}

/**
 * Check if a given object implements the RolLinkRequest interface.
 */
export function instanceOfRolLinkRequest(value: object): value is RolLinkRequest {
    return true;
}

export function RolLinkRequestFromJSON(json: any): RolLinkRequest {
    return RolLinkRequestFromJSONTyped(json, false);
}

export function RolLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rolId': json['rolId'] == null ? undefined : json['rolId'],
        'vincular': json['vincular'] == null ? undefined : json['vincular'],
    };
}

export function RolLinkRequestToJSON(json: any): RolLinkRequest {
    return RolLinkRequestToJSONTyped(json, false);
}

export function RolLinkRequestToJSONTyped(value?: RolLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rolId': value['rolId'],
        'vincular': value['vincular'],
    };
}

