/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortRequest } from './SortRequest';
import {
    SortRequestFromJSON,
    SortRequestFromJSONTyped,
    SortRequestToJSON,
    SortRequestToJSONTyped,
} from './SortRequest';
import type { FilterRequest } from './FilterRequest';
import {
    FilterRequestFromJSON,
    FilterRequestFromJSONTyped,
    FilterRequestToJSON,
    FilterRequestToJSONTyped,
} from './FilterRequest';

/**
 * 
 * @export
 * @interface SearchRequest
 */
export interface SearchRequest {
    /**
     * 
     * @type {Array<FilterRequest>}
     * @memberof SearchRequest
     */
    filters?: Array<FilterRequest>;
    /**
     * 
     * @type {Array<SortRequest>}
     * @memberof SearchRequest
     */
    sorts?: Array<SortRequest>;
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchRequest
     */
    size?: number;
}

/**
 * Check if a given object implements the SearchRequest interface.
 */
export function instanceOfSearchRequest(value: object): value is SearchRequest {
    return true;
}

export function SearchRequestFromJSON(json: any): SearchRequest {
    return SearchRequestFromJSONTyped(json, false);
}

export function SearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterRequestFromJSON)),
        'sorts': json['sorts'] == null ? undefined : ((json['sorts'] as Array<any>).map(SortRequestFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function SearchRequestToJSON(json: any): SearchRequest {
    return SearchRequestToJSONTyped(json, false);
}

export function SearchRequestToJSONTyped(value?: SearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterRequestToJSON)),
        'sorts': value['sorts'] == null ? undefined : ((value['sorts'] as Array<any>).map(SortRequestToJSON)),
        'page': value['page'],
        'size': value['size'],
    };
}

