/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SortRequest
 */
export interface SortRequest {
    /**
     * 
     * @type {string}
     * @memberof SortRequest
     */
    key?: string;
    /**
     * 
     * @type {SortRequestDirectionEnum}
     * @memberof SortRequest
     */
    direction?: SortRequestDirectionEnum;
}


/**
 * @export
 */
export const SortRequestDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type SortRequestDirectionEnum = typeof SortRequestDirectionEnum[keyof typeof SortRequestDirectionEnum];


/**
 * Check if a given object implements the SortRequest interface.
 */
export function instanceOfSortRequest(value: object): value is SortRequest {
    return true;
}

export function SortRequestFromJSON(json: any): SortRequest {
    return SortRequestFromJSONTyped(json, false);
}

export function SortRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'direction': json['direction'] == null ? undefined : json['direction'],
    };
}

export function SortRequestToJSON(json: any): SortRequest {
    return SortRequestToJSONTyped(json, false);
}

export function SortRequestToJSONTyped(value?: SortRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'direction': value['direction'],
    };
}

