/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BadRequestErrorResponseContent,
  ConflictErrorResponseContent,
  CreatePullRequestBody,
  CreatePullRequestCommentBody,
  ForbiddenErrorResponseContent,
  InternalServerErrorResponseContent,
  ListPullRequestCommentsBody,
  ListPullRequestsBody,
  MergePullRequestBody,
  NotFoundErrorResponseContent,
  PrStatus,
  PullRequestCommentDTO,
  PullRequestDTO,
  PullRequestMergeabilityDTO,
  ReviewPullRequestBody,
  SearchPullRequestsBody,
  UnauthorizedErrorResponseContent,
  UnprocessableEntityErrorResponseContent,
} from '../models/index';
import {
    BadRequestErrorResponseContentFromJSON,
    BadRequestErrorResponseContentToJSON,
    ConflictErrorResponseContentFromJSON,
    ConflictErrorResponseContentToJSON,
    CreatePullRequestBodyFromJSON,
    CreatePullRequestBodyToJSON,
    CreatePullRequestCommentBodyFromJSON,
    CreatePullRequestCommentBodyToJSON,
    ForbiddenErrorResponseContentFromJSON,
    ForbiddenErrorResponseContentToJSON,
    InternalServerErrorResponseContentFromJSON,
    InternalServerErrorResponseContentToJSON,
    ListPullRequestCommentsBodyFromJSON,
    ListPullRequestCommentsBodyToJSON,
    ListPullRequestsBodyFromJSON,
    ListPullRequestsBodyToJSON,
    MergePullRequestBodyFromJSON,
    MergePullRequestBodyToJSON,
    NotFoundErrorResponseContentFromJSON,
    NotFoundErrorResponseContentToJSON,
    PrStatusFromJSON,
    PrStatusToJSON,
    PullRequestCommentDTOFromJSON,
    PullRequestCommentDTOToJSON,
    PullRequestDTOFromJSON,
    PullRequestDTOToJSON,
    PullRequestMergeabilityDTOFromJSON,
    PullRequestMergeabilityDTOToJSON,
    ReviewPullRequestBodyFromJSON,
    ReviewPullRequestBodyToJSON,
    SearchPullRequestsBodyFromJSON,
    SearchPullRequestsBodyToJSON,
    UnauthorizedErrorResponseContentFromJSON,
    UnauthorizedErrorResponseContentToJSON,
    UnprocessableEntityErrorResponseContentFromJSON,
    UnprocessableEntityErrorResponseContentToJSON,
} from '../models/index';

export interface CreatePullRequestRequest {
    owner: string;
    repo: string;
    createPullRequestBody: CreatePullRequestBody;
}

export interface CreatePullRequestCommentRequest {
    owner: string;
    repo: string;
    prNumber: number;
    createPullRequestCommentBody: CreatePullRequestCommentBody;
}

export interface GetPullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface GetPullRequestMergeabilityRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface ListPullRequestCommentsRequest {
    owner: string;
    repo: string;
    prNumber: number;
}

export interface ListPullRequestsRequest {
    owner: string;
    repo: string;
    status?: PrStatus;
}

export interface MergePullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
    mergePullRequestBody: MergePullRequestBody;
}

export interface ReviewPullRequestRequest {
    owner: string;
    repo: string;
    prNumber: number;
    reviewPullRequestBody: ReviewPullRequestBody;
}

export interface SearchPullRequestsRequest {
    owner: string;
    repo: string;
    q: string;
    status?: PrStatus;
    page?: number;
    perPage?: number;
}

/**
 * DefaultApi - interface
 * 
 * @export
 * @interface DefaultApiInterface
 */
export interface DefaultApiInterface {
    /**
     * Crea un pull request entre dos ramas. RF07.1
     * @param {string} owner 
     * @param {string} repo 
     * @param {CreatePullRequestBody} createPullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestRaw(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    createPullRequest(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Agrega un comentario general o por linea a un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {CreatePullRequestCommentBody} createPullRequestCommentBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    createPullRequestCommentRaw(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestCommentDTO>>;

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    createPullRequestComment(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestCommentDTO>;

    /**
     * Obtiene el detalle de un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestRaw(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Obtiene el detalle de un pull request.
     */
    getPullRequest(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getPullRequestMergeabilityRaw(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestMergeabilityDTO>>;

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    getPullRequestMergeability(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestMergeabilityDTO>;

    /**
     * Lista comentarios de un pull request.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestCommentsRaw(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestCommentsBody>>;

    /**
     * Lista comentarios de un pull request.
     */
    listPullRequestComments(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestCommentsBody>;

    /**
     * Lista los pull requests del repositorio. RF07
     * @param {string} owner 
     * @param {string} repo 
     * @param {PrStatus} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    listPullRequestsRaw(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestsBody>>;

    /**
     * Lista los pull requests del repositorio. RF07
     */
    listPullRequests(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestsBody>;

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {MergePullRequestBody} mergePullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    mergePullRequestRaw(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    mergePullRequest(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     * @param {string} owner 
     * @param {string} repo 
     * @param {number} prNumber 
     * @param {ReviewPullRequestBody} reviewPullRequestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    reviewPullRequestRaw(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>>;

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    reviewPullRequest(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO>;

    /**
     * Busca pull requests por título o descripción.
     * @param {string} owner 
     * @param {string} repo 
     * @param {string} q 
     * @param {PrStatus} [status] 
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    searchPullRequestsRaw(requestParameters: SearchPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchPullRequestsBody>>;

    /**
     * Busca pull requests por título o descripción.
     */
    searchPullRequests(requestParameters: SearchPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchPullRequestsBody>;

}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI implements DefaultApiInterface {

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    async createPullRequestRaw(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['createPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestBody',
                'Required parameter "createPullRequestBody" was null or undefined when calling createPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestBodyToJSON(requestParameters['createPullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Crea un pull request entre dos ramas. RF07.1
     */
    async createPullRequest(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.createPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    async createPullRequestCommentRaw(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestCommentDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling createPullRequestComment().'
            );
        }

        if (requestParameters['createPullRequestCommentBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestCommentBody',
                'Required parameter "createPullRequestCommentBody" was null or undefined when calling createPullRequestComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestCommentBodyToJSON(requestParameters['createPullRequestCommentBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestCommentDTOFromJSON(jsonValue));
    }

    /**
     * Agrega un comentario general o por linea a un pull request.
     */
    async createPullRequestComment(requestParameters: CreatePullRequestCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestCommentDTO> {
        const response = await this.createPullRequestCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Obtiene el detalle de un pull request.
     */
    async getPullRequestRaw(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling getPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Obtiene el detalle de un pull request.
     */
    async getPullRequest(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.getPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    async getPullRequestMergeabilityRaw(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestMergeabilityDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling getPullRequestMergeability().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}/mergeability`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestMergeabilityDTOFromJSON(jsonValue));
    }

    /**
     * Evalua conflictos y mergeabilidad antes de merge. RF07.3
     */
    async getPullRequestMergeability(requestParameters: GetPullRequestMergeabilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestMergeabilityDTO> {
        const response = await this.getPullRequestMergeabilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lista comentarios de un pull request.
     */
    async listPullRequestCommentsRaw(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestCommentsBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling listPullRequestComments().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling listPullRequestComments().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling listPullRequestComments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}/comments`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPullRequestCommentsBodyFromJSON(jsonValue));
    }

    /**
     * Lista comentarios de un pull request.
     */
    async listPullRequestComments(requestParameters: ListPullRequestCommentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestCommentsBody> {
        const response = await this.listPullRequestCommentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lista los pull requests del repositorio. RF07
     */
    async listPullRequestsRaw(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPullRequestsBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling listPullRequests().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling listPullRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPullRequestsBodyFromJSON(jsonValue));
    }

    /**
     * Lista los pull requests del repositorio. RF07
     */
    async listPullRequests(requestParameters: ListPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPullRequestsBody> {
        const response = await this.listPullRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    async mergePullRequestRaw(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling mergePullRequest().'
            );
        }

        if (requestParameters['mergePullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'mergePullRequestBody',
                'Required parameter "mergePullRequestBody" was null or undefined when calling mergePullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}/merge`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MergePullRequestBodyToJSON(requestParameters['mergePullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Ejecuta merge de un pull request aprobado y sin conflictos.
     */
    async mergePullRequest(requestParameters: MergePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.mergePullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    async reviewPullRequestRaw(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequestDTO>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['prNumber'] == null) {
            throw new runtime.RequiredError(
                'prNumber',
                'Required parameter "prNumber" was null or undefined when calling reviewPullRequest().'
            );
        }

        if (requestParameters['reviewPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'reviewPullRequestBody',
                'Required parameter "reviewPullRequestBody" was null or undefined when calling reviewPullRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/{prNumber}/review`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))).replace(`{${"prNumber"}}`, encodeURIComponent(String(requestParameters['prNumber']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewPullRequestBodyToJSON(requestParameters['reviewPullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestDTOFromJSON(jsonValue));
    }

    /**
     * Aprueba o solicita cambios en un pull request. RF07.2
     */
    async reviewPullRequest(requestParameters: ReviewPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequestDTO> {
        const response = await this.reviewPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Busca pull requests por título o descripción.
     */
    async searchPullRequestsRaw(requestParameters: SearchPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchPullRequestsBody>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling searchPullRequests().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling searchPullRequests().'
            );
        }

        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchPullRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("smithy.api.httpBearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/repos/{owner}/{repo}/pulls/search`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchPullRequestsBodyFromJSON(jsonValue));
    }

    /**
     * Busca pull requests por título o descripción.
     */
    async searchPullRequests(requestParameters: SearchPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchPullRequestsBody> {
        const response = await this.searchPullRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
