/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePullRequestBody
 */
export interface CreatePullRequestBody {
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestBody
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestBody
     */
    sourceBranch: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePullRequestBody
     */
    targetBranch: string;
}

/**
 * Check if a given object implements the CreatePullRequestBody interface.
 */
export function instanceOfCreatePullRequestBody(value: object): value is CreatePullRequestBody {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sourceBranch' in value) || value['sourceBranch'] === undefined) return false;
    if (!('targetBranch' in value) || value['targetBranch'] === undefined) return false;
    return true;
}

export function CreatePullRequestBodyFromJSON(json: any): CreatePullRequestBody {
    return CreatePullRequestBodyFromJSONTyped(json, false);
}

export function CreatePullRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePullRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceBranch': json['sourceBranch'],
        'targetBranch': json['targetBranch'],
    };
}

export function CreatePullRequestBodyToJSON(json: any): CreatePullRequestBody {
    return CreatePullRequestBodyToJSONTyped(json, false);
}

export function CreatePullRequestBodyToJSONTyped(value?: CreatePullRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'sourceBranch': value['sourceBranch'],
        'targetBranch': value['targetBranch'],
    };
}

