/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PullRequestDTO } from './PullRequestDTO';
import {
    PullRequestDTOFromJSON,
    PullRequestDTOFromJSONTyped,
    PullRequestDTOToJSON,
    PullRequestDTOToJSONTyped,
} from './PullRequestDTO';

/**
 * 
 * @export
 * @interface ListPullRequestsBody
 */
export interface ListPullRequestsBody {
    /**
     * 
     * @type {Array<PullRequestDTO>}
     * @memberof ListPullRequestsBody
     */
    pullRequests: Array<PullRequestDTO>;
}

/**
 * Check if a given object implements the ListPullRequestsBody interface.
 */
export function instanceOfListPullRequestsBody(value: object): value is ListPullRequestsBody {
    if (!('pullRequests' in value) || value['pullRequests'] === undefined) return false;
    return true;
}

export function ListPullRequestsBodyFromJSON(json: any): ListPullRequestsBody {
    return ListPullRequestsBodyFromJSONTyped(json, false);
}

export function ListPullRequestsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPullRequestsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'pullRequests': ((json['pullRequests'] as Array<any>).map(PullRequestDTOFromJSON)),
    };
}

export function ListPullRequestsBodyToJSON(json: any): ListPullRequestsBody {
    return ListPullRequestsBodyToJSONTyped(json, false);
}

export function ListPullRequestsBodyToJSONTyped(value?: ListPullRequestsBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pullRequests': ((value['pullRequests'] as Array<any>).map(PullRequestDTOToJSON)),
    };
}

