/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MergeStrategy } from './MergeStrategy';
import {
    MergeStrategyFromJSON,
    MergeStrategyFromJSONTyped,
    MergeStrategyToJSON,
    MergeStrategyToJSONTyped,
} from './MergeStrategy';

/**
 * 
 * @export
 * @interface MergePullRequestBody
 */
export interface MergePullRequestBody {
    /**
     * 
     * @type {MergeStrategy}
     * @memberof MergePullRequestBody
     */
    strategy: MergeStrategy;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestBody
     */
    commitMessage?: string;
}



/**
 * Check if a given object implements the MergePullRequestBody interface.
 */
export function instanceOfMergePullRequestBody(value: object): value is MergePullRequestBody {
    if (!('strategy' in value) || value['strategy'] === undefined) return false;
    return true;
}

export function MergePullRequestBodyFromJSON(json: any): MergePullRequestBody {
    return MergePullRequestBodyFromJSONTyped(json, false);
}

export function MergePullRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergePullRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'strategy': MergeStrategyFromJSON(json['strategy']),
        'commitMessage': json['commitMessage'] == null ? undefined : json['commitMessage'],
    };
}

export function MergePullRequestBodyToJSON(json: any): MergePullRequestBody {
    return MergePullRequestBodyToJSONTyped(json, false);
}

export function MergePullRequestBodyToJSONTyped(value?: MergePullRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strategy': MergeStrategyToJSON(value['strategy']),
        'commitMessage': value['commitMessage'],
    };
}

