/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MergeStrategy = {
    Merge: 'merge',
    Squash: 'squash',
    Rebase: 'rebase'
} as const;
export type MergeStrategy = typeof MergeStrategy[keyof typeof MergeStrategy];


export function instanceOfMergeStrategy(value: any): boolean {
    for (const key in MergeStrategy) {
        if (Object.prototype.hasOwnProperty.call(MergeStrategy, key)) {
            if (MergeStrategy[key as keyof typeof MergeStrategy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MergeStrategyFromJSON(json: any): MergeStrategy {
    return MergeStrategyFromJSONTyped(json, false);
}

export function MergeStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeStrategy {
    return json as MergeStrategy;
}

export function MergeStrategyToJSON(value?: MergeStrategy | null): any {
    return value as any;
}

export function MergeStrategyToJSONTyped(value: any, ignoreDiscriminator: boolean): MergeStrategy {
    return value as MergeStrategy;
}

