/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotFoundErrorResponseContent
 */
export interface NotFoundErrorResponseContent {
    /**
     * 
     * @type {string}
     * @memberof NotFoundErrorResponseContent
     */
    message: string;
}

/**
 * Check if a given object implements the NotFoundErrorResponseContent interface.
 */
export function instanceOfNotFoundErrorResponseContent(value: object): value is NotFoundErrorResponseContent {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function NotFoundErrorResponseContentFromJSON(json: any): NotFoundErrorResponseContent {
    return NotFoundErrorResponseContentFromJSONTyped(json, false);
}

export function NotFoundErrorResponseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFoundErrorResponseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NotFoundErrorResponseContentToJSON(json: any): NotFoundErrorResponseContent {
    return NotFoundErrorResponseContentToJSONTyped(json, false);
}

export function NotFoundErrorResponseContentToJSONTyped(value?: NotFoundErrorResponseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

