/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): boolean {
    if (!('page' in value)) return false;
    if (!('perPage' in value)) return false;
    if (!('total' in value)) return false;
    if (!('totalPages' in value)) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'perPage': json['perPage'],
        'total': json['total'],
        'totalPages': json['totalPages'],
    };
}

export function PaginationMetaToJSON(value?: PaginationMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'perPage': value['perPage'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

