/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PrStatus = {
    Open: 'open',
    Closed: 'closed',
    Merged: 'merged'
} as const;
export type PrStatus = typeof PrStatus[keyof typeof PrStatus];


export function instanceOfPrStatus(value: any): boolean {
    for (const key in PrStatus) {
        if (Object.prototype.hasOwnProperty.call(PrStatus, key)) {
            if (PrStatus[key as keyof typeof PrStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PrStatusFromJSON(json: any): PrStatus {
    return PrStatusFromJSONTyped(json, false);
}

export function PrStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrStatus {
    return json as PrStatus;
}

export function PrStatusToJSON(value?: PrStatus | null): any {
    return value as any;
}

export function PrStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PrStatus {
    return value as PrStatus;
}

