/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrStatus } from './PrStatus';
import {
    PrStatusFromJSON,
    PrStatusFromJSONTyped,
    PrStatusToJSON,
    PrStatusToJSONTyped,
} from './PrStatus';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
    AuthorSummaryToJSONTyped,
} from './AuthorSummary';

/**
 * 
 * @export
 * @interface PullRequestDTO
 */
export interface PullRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    repoId: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequestDTO
     */
    number: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    sourceBranch: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    targetBranch: string;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof PullRequestDTO
     */
    author: AuthorSummary;
    /**
     * 
     * @type {PrStatus}
     * @memberof PullRequestDTO
     */
    status: PrStatus;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequestDTO
     */
    hasConflicts: boolean;
    /**
     * 
     * @type {number}
     * @memberof PullRequestDTO
     */
    commitsCount: number;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestDTO
     */
    mergedAt?: string;
}



/**
 * Check if a given object implements the PullRequestDTO interface.
 */
export function instanceOfPullRequestDTO(value: object): value is PullRequestDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('repoId' in value) || value['repoId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('sourceBranch' in value) || value['sourceBranch'] === undefined) return false;
    if (!('targetBranch' in value) || value['targetBranch'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('hasConflicts' in value) || value['hasConflicts'] === undefined) return false;
    if (!('commitsCount' in value) || value['commitsCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PullRequestDTOFromJSON(json: any): PullRequestDTO {
    return PullRequestDTOFromJSONTyped(json, false);
}

export function PullRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'repoId': json['repoId'],
        'number': json['number'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'sourceBranch': json['sourceBranch'],
        'targetBranch': json['targetBranch'],
        'author': AuthorSummaryFromJSON(json['author']),
        'status': PrStatusFromJSON(json['status']),
        'hasConflicts': json['hasConflicts'],
        'commitsCount': json['commitsCount'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'mergedAt': json['mergedAt'] == null ? undefined : json['mergedAt'],
    };
}

export function PullRequestDTOToJSON(json: any): PullRequestDTO {
    return PullRequestDTOToJSONTyped(json, false);
}

export function PullRequestDTOToJSONTyped(value?: PullRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'repoId': value['repoId'],
        'number': value['number'],
        'title': value['title'],
        'description': value['description'],
        'sourceBranch': value['sourceBranch'],
        'targetBranch': value['targetBranch'],
        'author': AuthorSummaryToJSON(value['author']),
        'status': PrStatusToJSON(value['status']),
        'hasConflicts': value['hasConflicts'],
        'commitsCount': value['commitsCount'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'mergedAt': value['mergedAt'],
    };
}

