/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorSummary } from './AuthorSummary';
import {
    AuthorSummaryFromJSON,
    AuthorSummaryFromJSONTyped,
    AuthorSummaryToJSON,
    AuthorSummaryToJSONTyped,
} from './AuthorSummary';

/**
 * 
 * @export
 * @interface PullRequestCommentDTO
 */
export interface PullRequestCommentDTO {
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    pullRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    filePath?: string;
    /**
     * 
     * @type {number}
     * @memberof PullRequestCommentDTO
     */
    lineNumber?: number;
    /**
     * 
     * @type {AuthorSummary}
     * @memberof PullRequestCommentDTO
     */
    author: AuthorSummary;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PullRequestCommentDTO
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PullRequestCommentDTO interface.
 */
export function instanceOfPullRequestCommentDTO(value: object): value is PullRequestCommentDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pullRequestId' in value) || value['pullRequestId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PullRequestCommentDTOFromJSON(json: any): PullRequestCommentDTO {
    return PullRequestCommentDTOFromJSONTyped(json, false);
}

export function PullRequestCommentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestCommentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pullRequestId': json['pullRequestId'],
        'body': json['body'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'lineNumber': json['lineNumber'] == null ? undefined : json['lineNumber'],
        'author': AuthorSummaryFromJSON(json['author']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function PullRequestCommentDTOToJSON(json: any): PullRequestCommentDTO {
    return PullRequestCommentDTOToJSONTyped(json, false);
}

export function PullRequestCommentDTOToJSONTyped(value?: PullRequestCommentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pullRequestId': value['pullRequestId'],
        'body': value['body'],
        'filePath': value['filePath'],
        'lineNumber': value['lineNumber'],
        'author': AuthorSummaryToJSON(value['author']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

