/* tslint:disable */
/* eslint-disable */
/**
 * GitHub Pull Request API
 * Servicio dedicado para pull requests y comentarios de pull requests.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ReviewDecision = {
    Approved: 'approved',
    ChangesRequested: 'changes_requested',
    Commented: 'commented'
} as const;
export type ReviewDecision = typeof ReviewDecision[keyof typeof ReviewDecision];


export function instanceOfReviewDecision(value: any): boolean {
    for (const key in ReviewDecision) {
        if (Object.prototype.hasOwnProperty.call(ReviewDecision, key)) {
            if (ReviewDecision[key as keyof typeof ReviewDecision] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReviewDecisionFromJSON(json: any): ReviewDecision {
    return ReviewDecisionFromJSONTyped(json, false);
}

export function ReviewDecisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewDecision {
    return json as ReviewDecision;
}

export function ReviewDecisionToJSON(value?: ReviewDecision | null): any {
    return value as any;
}

export function ReviewDecisionToJSONTyped(value: any, ignoreDiscriminator: boolean): ReviewDecision {
    return value as ReviewDecision;
}

