/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Commit padre
 * @export
 * @interface CommitParent
 */
export interface CommitParent {
    /**
     * 
     * @type {string}
     * @memberof CommitParent
     */
    sha: string;
    /**
     * 
     * @type {string}
     * @memberof CommitParent
     */
    url?: string;
}

/**
 * Check if a given object implements the CommitParent interface.
 */
export function instanceOfCommitParent(value: object): boolean {
    if (!('sha' in value)) return false;
    return true;
}

export function CommitParentFromJSON(json: any): CommitParent {
    return CommitParentFromJSONTyped(json, false);
}

export function CommitParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitParent {
    if (json == null) {
        return json;
    }
    return {
        
        'sha': json['sha'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function CommitParentToJSON(value?: CommitParent | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sha': value['sha'],
        'url': value['url'],
    };
}

