/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitParent } from './CommitParent';
import {
    CommitParentFromJSON,
    CommitParentFromJSONTyped,
    CommitParentToJSON,
} from './CommitParent';
import type { CommitSignature } from './CommitSignature';
import {
    CommitSignatureFromJSON,
    CommitSignatureFromJSONTyped,
    CommitSignatureToJSON,
} from './CommitSignature';

/**
 * Commit completo
 * @export
 * @interface CommitDTO
 */
export interface CommitDTO {
    /**
     * 
     * @type {string}
     * @memberof CommitDTO
     */
    sha: string;
    /**
     * 
     * @type {string}
     * @memberof CommitDTO
     */
    message: string;
    /**
     * 
     * @type {CommitSignature}
     * @memberof CommitDTO
     */
    author: CommitSignature;
    /**
     * 
     * @type {CommitSignature}
     * @memberof CommitDTO
     */
    committer: CommitSignature;
    /**
     * 
     * @type {string}
     * @memberof CommitDTO
     */
    htmlUrl?: string;
    /**
     * 
     * @type {Array<CommitParent>}
     * @memberof CommitDTO
     */
    parents?: Array<CommitParent>;
}

/**
 * Check if a given object implements the CommitDTO interface.
 */
export function instanceOfCommitDTO(value: object): boolean {
    if (!('sha' in value)) return false;
    if (!('message' in value)) return false;
    if (!('author' in value)) return false;
    if (!('committer' in value)) return false;
    return true;
}

export function CommitDTOFromJSON(json: any): CommitDTO {
    return CommitDTOFromJSONTyped(json, false);
}

export function CommitDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'sha': json['sha'],
        'message': json['message'],
        'author': CommitSignatureFromJSON(json['author']),
        'committer': CommitSignatureFromJSON(json['committer']),
        'htmlUrl': json['htmlUrl'] == null ? undefined : json['htmlUrl'],
        'parents': json['parents'] == null ? undefined : ((json['parents'] as Array<any>).map(CommitParentFromJSON)),
    };
}

export function CommitDTOToJSON(value?: CommitDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sha': value['sha'],
        'message': value['message'],
        'author': CommitSignatureToJSON(value['author']),
        'committer': CommitSignatureToJSON(value['committer']),
        'htmlUrl': value['htmlUrl'],
        'parents': value['parents'] == null ? undefined : ((value['parents'] as Array<any>).map(CommitParentToJSON)),
    };
}

