/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Archivo cambiado en un commit o comparacion
 * @export
 * @interface CommitFile
 */
export interface CommitFile {
    /**
     * 
     * @type {string}
     * @memberof CommitFile
     */
    filename: string;
    /**
     * added, modified, deleted, renamed
     * @type {string}
     * @memberof CommitFile
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof CommitFile
     */
    additions?: number;
    /**
     * 
     * @type {number}
     * @memberof CommitFile
     */
    deletions?: number;
    /**
     * 
     * @type {number}
     * @memberof CommitFile
     */
    changes?: number;
    /**
     * Diff del archivo
     * @type {string}
     * @memberof CommitFile
     */
    patch?: string;
}

/**
 * Check if a given object implements the CommitFile interface.
 */
export function instanceOfCommitFile(value: object): boolean {
    if (!('filename' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function CommitFileFromJSON(json: any): CommitFile {
    return CommitFileFromJSONTyped(json, false);
}

export function CommitFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitFile {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'status': json['status'],
        'additions': json['additions'] == null ? undefined : json['additions'],
        'deletions': json['deletions'] == null ? undefined : json['deletions'],
        'changes': json['changes'] == null ? undefined : json['changes'],
        'patch': json['patch'] == null ? undefined : json['patch'],
    };
}

export function CommitFileToJSON(value?: CommitFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filename': value['filename'],
        'status': value['status'],
        'additions': value['additions'],
        'deletions': value['deletions'],
        'changes': value['changes'],
        'patch': value['patch'],
    };
}

