/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitSignature } from './CommitSignature';
import {
    CommitSignatureFromJSON,
    CommitSignatureFromJSONTyped,
    CommitSignatureToJSON,
} from './CommitSignature';

/**
 * Resumen de commit (para responses de operaciones)
 * @export
 * @interface CommitSummaryDTO
 */
export interface CommitSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof CommitSummaryDTO
     */
    sha: string;
    /**
     * 
     * @type {string}
     * @memberof CommitSummaryDTO
     */
    message: string;
    /**
     * 
     * @type {CommitSignature}
     * @memberof CommitSummaryDTO
     */
    author: CommitSignature;
    /**
     * 
     * @type {CommitSignature}
     * @memberof CommitSummaryDTO
     */
    committer: CommitSignature;
    /**
     * 
     * @type {string}
     * @memberof CommitSummaryDTO
     */
    htmlUrl?: string;
}

/**
 * Check if a given object implements the CommitSummaryDTO interface.
 */
export function instanceOfCommitSummaryDTO(value: object): boolean {
    if (!('sha' in value)) return false;
    if (!('message' in value)) return false;
    if (!('author' in value)) return false;
    if (!('committer' in value)) return false;
    return true;
}

export function CommitSummaryDTOFromJSON(json: any): CommitSummaryDTO {
    return CommitSummaryDTOFromJSONTyped(json, false);
}

export function CommitSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'sha': json['sha'],
        'message': json['message'],
        'author': CommitSignatureFromJSON(json['author']),
        'committer': CommitSignatureFromJSON(json['committer']),
        'htmlUrl': json['htmlUrl'] == null ? undefined : json['htmlUrl'],
    };
}

export function CommitSummaryDTOToJSON(value?: CommitSummaryDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sha': value['sha'],
        'message': value['message'],
        'author': CommitSignatureToJSON(value['author']),
        'committer': CommitSignatureToJSON(value['committer']),
        'htmlUrl': value['htmlUrl'],
    };
}

