/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Firma de commit (autor o committer)
 * @export
 * @interface CommitSignature
 */
export interface CommitSignature {
    /**
     * 
     * @type {string}
     * @memberof CommitSignature
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CommitSignature
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CommitSignature
     */
    date: string;
}

/**
 * Check if a given object implements the CommitSignature interface.
 */
export function instanceOfCommitSignature(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('email' in value)) return false;
    if (!('date' in value)) return false;
    return true;
}

export function CommitSignatureFromJSON(json: any): CommitSignature {
    return CommitSignatureFromJSONTyped(json, false);
}

export function CommitSignatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommitSignature {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'date': json['date'],
    };
}

export function CommitSignatureToJSON(value?: CommitSignature | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'date': value['date'],
    };
}

