/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitDTO } from './CommitDTO';
import {
    CommitDTOFromJSON,
    CommitDTOFromJSONTyped,
    CommitDTOToJSON,
} from './CommitDTO';
import type { CommitFile } from './CommitFile';
import {
    CommitFileFromJSON,
    CommitFileFromJSONTyped,
    CommitFileToJSON,
} from './CommitFile';

/**
 * Comparacion entre branches (HU-20)
 * @export
 * @interface CompareDTO
 */
export interface CompareDTO {
    /**
     * 
     * @type {Array<CommitDTO>}
     * @memberof CompareDTO
     */
    commits: Array<CommitDTO>;
    /**
     * 
     * @type {number}
     * @memberof CompareDTO
     */
    totalCommits: number;
    /**
     * 
     * @type {Array<CommitFile>}
     * @memberof CompareDTO
     */
    files: Array<CommitFile>;
    /**
     * 
     * @type {number}
     * @memberof CompareDTO
     */
    aheadBy: number;
    /**
     * 
     * @type {number}
     * @memberof CompareDTO
     */
    behindBy: number;
}

/**
 * Check if a given object implements the CompareDTO interface.
 */
export function instanceOfCompareDTO(value: object): boolean {
    if (!('commits' in value)) return false;
    if (!('totalCommits' in value)) return false;
    if (!('files' in value)) return false;
    if (!('aheadBy' in value)) return false;
    if (!('behindBy' in value)) return false;
    return true;
}

export function CompareDTOFromJSON(json: any): CompareDTO {
    return CompareDTOFromJSONTyped(json, false);
}

export function CompareDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompareDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'commits': ((json['commits'] as Array<any>).map(CommitDTOFromJSON)),
        'totalCommits': json['totalCommits'],
        'files': ((json['files'] as Array<any>).map(CommitFileFromJSON)),
        'aheadBy': json['aheadBy'],
        'behindBy': json['behindBy'],
    };
}

export function CompareDTOToJSON(value?: CompareDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'commits': ((value['commits'] as Array<any>).map(CommitDTOToJSON)),
        'totalCommits': value['totalCommits'],
        'files': ((value['files'] as Array<any>).map(CommitFileToJSON)),
        'aheadBy': value['aheadBy'],
        'behindBy': value['behindBy'],
    };
}

