/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
} from './Identity';

/**
 * 
 * @export
 * @interface CreateFileBody
 */
export interface CreateFileBody {
    /**
     * Contenido binario del archivo (maximo 10MB)
     * @type {string}
     * @memberof CreateFileBody
     */
    content: string;
    /**
     * Mensaje del commit
     * @type {string}
     * @memberof CreateFileBody
     */
    message: string;
    /**
     * Branch destino (default: rama por defecto)
     * @type {string}
     * @memberof CreateFileBody
     */
    branch?: string;
    /**
     * 
     * @type {Identity}
     * @memberof CreateFileBody
     */
    author?: Identity;
    /**
     * 
     * @type {Identity}
     * @memberof CreateFileBody
     */
    committer?: Identity;
}

/**
 * Check if a given object implements the CreateFileBody interface.
 */
export function instanceOfCreateFileBody(value: object): boolean {
    if (!('content' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function CreateFileBodyFromJSON(json: any): CreateFileBody {
    return CreateFileBodyFromJSONTyped(json, false);
}

export function CreateFileBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileBody {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'message': json['message'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'author': json['author'] == null ? undefined : IdentityFromJSON(json['author']),
        'committer': json['committer'] == null ? undefined : IdentityFromJSON(json['committer']),
    };
}

export function CreateFileBodyToJSON(value?: CreateFileBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'message': value['message'],
        'branch': value['branch'],
        'author': IdentityToJSON(value['author']),
        'committer': IdentityToJSON(value['committer']),
    };
}

