/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFolderBody
 */
export interface CreateFolderBody {
    /**
     * Nombre/ruta de la carpeta
     * @type {string}
     * @memberof CreateFolderBody
     */
    path: string;
    /**
     * Mensaje del commit
     * @type {string}
     * @memberof CreateFolderBody
     */
    message: string;
    /**
     * Branch destino
     * @type {string}
     * @memberof CreateFolderBody
     */
    branch?: string;
}

/**
 * Check if a given object implements the CreateFolderBody interface.
 */
export function instanceOfCreateFolderBody(value: object): boolean {
    if (!('path' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function CreateFolderBodyFromJSON(json: any): CreateFolderBody {
    return CreateFolderBodyFromJSONTyped(json, false);
}

export function CreateFolderBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolderBody {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'message': json['message'],
        'branch': json['branch'] == null ? undefined : json['branch'],
    };
}

export function CreateFolderBodyToJSON(value?: CreateFolderBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'path': value['path'],
        'message': value['message'],
        'branch': value['branch'],
    };
}

