/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitSummaryDTO } from './CommitSummaryDTO';
import {
    CommitSummaryDTOFromJSON,
    CommitSummaryDTOFromJSONTyped,
    CommitSummaryDTOToJSON,
} from './CommitSummaryDTO';

/**
 * 
 * @export
 * @interface DeleteFileResponseBody
 */
export interface DeleteFileResponseBody {
    /**
     * 
     * @type {CommitSummaryDTO}
     * @memberof DeleteFileResponseBody
     */
    commit: CommitSummaryDTO;
}

/**
 * Check if a given object implements the DeleteFileResponseBody interface.
 */
export function instanceOfDeleteFileResponseBody(value: object): boolean {
    if (!('commit' in value)) return false;
    return true;
}

export function DeleteFileResponseBodyFromJSON(json: any): DeleteFileResponseBody {
    return DeleteFileResponseBodyFromJSONTyped(json, false);
}

export function DeleteFileResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFileResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': CommitSummaryDTOFromJSON(json['commit']),
    };
}

export function DeleteFileResponseBodyToJSON(value?: DeleteFileResponseBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'commit': CommitSummaryDTOToJSON(value['commit']),
    };
}

