/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitObjectType } from './GitObjectType';
import {
    GitObjectTypeFromJSON,
    GitObjectTypeFromJSONTyped,
    GitObjectTypeToJSON,
} from './GitObjectType';

/**
 * Contenido de archivo (respuesta GET para archivos)
 * @export
 * @interface FileContentDTO
 */
export interface FileContentDTO {
    /**
     * 
     * @type {string}
     * @memberof FileContentDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FileContentDTO
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof FileContentDTO
     */
    sha: string;
    /**
     * 
     * @type {GitObjectType}
     * @memberof FileContentDTO
     */
    type: GitObjectType;
    /**
     * 
     * @type {number}
     * @memberof FileContentDTO
     */
    size?: number;
    /**
     * "base64" para archivos con contenido
     * @type {string}
     * @memberof FileContentDTO
     */
    encoding?: string;
    /**
     * Contenido del archivo en base64
     * @type {string}
     * @memberof FileContentDTO
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof FileContentDTO
     */
    downloadUrl: string;
    /**
     * 
     * @type {string}
     * @memberof FileContentDTO
     */
    htmlUrl?: string;
    /**
     * SHA del ultimo commit que modifico el archivo
     * @type {string}
     * @memberof FileContentDTO
     */
    lastCommitSha?: string;
}

/**
 * Check if a given object implements the FileContentDTO interface.
 */
export function instanceOfFileContentDTO(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('path' in value)) return false;
    if (!('sha' in value)) return false;
    if (!('type' in value)) return false;
    if (!('downloadUrl' in value)) return false;
    return true;
}

export function FileContentDTOFromJSON(json: any): FileContentDTO {
    return FileContentDTOFromJSONTyped(json, false);
}

export function FileContentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileContentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'],
        'sha': json['sha'],
        'type': GitObjectTypeFromJSON(json['type']),
        'size': json['size'] == null ? undefined : json['size'],
        'encoding': json['encoding'] == null ? undefined : json['encoding'],
        'content': json['content'] == null ? undefined : json['content'],
        'downloadUrl': json['downloadUrl'],
        'htmlUrl': json['htmlUrl'] == null ? undefined : json['htmlUrl'],
        'lastCommitSha': json['lastCommitSha'] == null ? undefined : json['lastCommitSha'],
    };
}

export function FileContentDTOToJSON(value?: FileContentDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'path': value['path'],
        'sha': value['sha'],
        'type': GitObjectTypeToJSON(value['type']),
        'size': value['size'],
        'encoding': value['encoding'],
        'content': value['content'],
        'downloadUrl': value['downloadUrl'],
        'htmlUrl': value['htmlUrl'],
        'lastCommitSha': value['lastCommitSha'],
    };
}

