/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitSummaryDTO } from './CommitSummaryDTO';
import {
    CommitSummaryDTOFromJSON,
    CommitSummaryDTOFromJSONTyped,
    CommitSummaryDTOToJSON,
} from './CommitSummaryDTO';
import type { FileContentDTO } from './FileContentDTO';
import {
    FileContentDTOFromJSON,
    FileContentDTOFromJSONTyped,
    FileContentDTOToJSON,
} from './FileContentDTO';

/**
 * Respuesta de operacion de archivo (create/update/delete)
 * @export
 * @interface FileOperationResponse
 */
export interface FileOperationResponse {
    /**
     * 
     * @type {FileContentDTO}
     * @memberof FileOperationResponse
     */
    content: FileContentDTO;
    /**
     * 
     * @type {CommitSummaryDTO}
     * @memberof FileOperationResponse
     */
    commit: CommitSummaryDTO;
}

/**
 * Check if a given object implements the FileOperationResponse interface.
 */
export function instanceOfFileOperationResponse(value: object): boolean {
    if (!('content' in value)) return false;
    if (!('commit' in value)) return false;
    return true;
}

export function FileOperationResponseFromJSON(json: any): FileOperationResponse {
    return FileOperationResponseFromJSONTyped(json, false);
}

export function FileOperationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOperationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': FileContentDTOFromJSON(json['content']),
        'commit': CommitSummaryDTOFromJSON(json['commit']),
    };
}

export function FileOperationResponseToJSON(value?: FileOperationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': FileContentDTOToJSON(value['content']),
        'commit': CommitSummaryDTOToJSON(value['commit']),
    };
}

