/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitDTO } from './CommitDTO';
import {
    CommitDTOFromJSON,
    CommitDTOFromJSONTyped,
    CommitDTOToJSON,
} from './CommitDTO';
import type { CommitFile } from './CommitFile';
import {
    CommitFileFromJSON,
    CommitFileFromJSONTyped,
    CommitFileToJSON,
} from './CommitFile';

/**
 * 
 * @export
 * @interface GetCommitBody
 */
export interface GetCommitBody {
    /**
     * 
     * @type {CommitDTO}
     * @memberof GetCommitBody
     */
    commit: CommitDTO;
    /**
     * Archivos modificados en este commit
     * @type {Array<CommitFile>}
     * @memberof GetCommitBody
     */
    files?: Array<CommitFile>;
}

/**
 * Check if a given object implements the GetCommitBody interface.
 */
export function instanceOfGetCommitBody(value: object): boolean {
    if (!('commit' in value)) return false;
    return true;
}

export function GetCommitBodyFromJSON(json: any): GetCommitBody {
    return GetCommitBodyFromJSONTyped(json, false);
}

export function GetCommitBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCommitBody {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': CommitDTOFromJSON(json['commit']),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(CommitFileFromJSON)),
    };
}

export function GetCommitBodyToJSON(value?: GetCommitBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'commit': CommitDTOToJSON(value['commit']),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(CommitFileToJSON)),
    };
}

