/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DirectoryEntryDTO } from './DirectoryEntryDTO';
import {
    DirectoryEntryDTOFromJSON,
    DirectoryEntryDTOFromJSONTyped,
    DirectoryEntryDTOToJSON,
} from './DirectoryEntryDTO';
import type { FileContentDTO } from './FileContentDTO';
import {
    FileContentDTOFromJSON,
    FileContentDTOFromJSONTyped,
    FileContentDTOToJSON,
} from './FileContentDTO';

/**
 * Respuesta polimorfica: archivo o lista de entradas
 * @export
 * @interface GetFileContentBody
 */
export interface GetFileContentBody {
    /**
     * 
     * @type {FileContentDTO}
     * @memberof GetFileContentBody
     */
    file?: FileContentDTO;
    /**
     * Si es directorio, contiene la lista de entradas
     * @type {Array<DirectoryEntryDTO>}
     * @memberof GetFileContentBody
     */
    entries?: Array<DirectoryEntryDTO>;
}

/**
 * Check if a given object implements the GetFileContentBody interface.
 */
export function instanceOfGetFileContentBody(value: object): boolean {
    return true;
}

export function GetFileContentBodyFromJSON(json: any): GetFileContentBody {
    return GetFileContentBodyFromJSONTyped(json, false);
}

export function GetFileContentBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFileContentBody {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'] == null ? undefined : FileContentDTOFromJSON(json['file']),
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(DirectoryEntryDTOFromJSON)),
    };
}

export function GetFileContentBodyToJSON(value?: GetFileContentBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': FileContentDTOToJSON(value['file']),
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(DirectoryEntryDTOToJSON)),
    };
}

