/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tipo de objeto Git (archivo o directorio)
 * @export
 */
export const GitObjectType = {
    File: 'file',
    Dir: 'dir'
} as const;
export type GitObjectType = typeof GitObjectType[keyof typeof GitObjectType];


export function instanceOfGitObjectType(value: any): boolean {
    return Object.values(GitObjectType).includes(value);
}

export function GitObjectTypeFromJSON(json: any): GitObjectType {
    return GitObjectTypeFromJSONTyped(json, false);
}

export function GitObjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitObjectType {
    return json as GitObjectType;
}

export function GitObjectTypeToJSON(value?: GitObjectType | null): any {
    return value as any;
}

