/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitDTO } from './CommitDTO';
import {
    CommitDTOFromJSON,
    CommitDTOFromJSONTyped,
    CommitDTOToJSON,
} from './CommitDTO';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface ListCommitsBody
 */
export interface ListCommitsBody {
    /**
     * 
     * @type {Array<CommitDTO>}
     * @memberof ListCommitsBody
     */
    commits: Array<CommitDTO>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ListCommitsBody
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the ListCommitsBody interface.
 */
export function instanceOfListCommitsBody(value: object): boolean {
    if (!('commits' in value)) return false;
    if (!('pagination' in value)) return false;
    return true;
}

export function ListCommitsBodyFromJSON(json: any): ListCommitsBody {
    return ListCommitsBodyFromJSONTyped(json, false);
}

export function ListCommitsBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCommitsBody {
    if (json == null) {
        return json;
    }
    return {
        
        'commits': ((json['commits'] as Array<any>).map(CommitDTOFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function ListCommitsBodyToJSON(value?: ListCommitsBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'commits': ((value['commits'] as Array<any>).map(CommitDTOToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

