/* tslint:disable */
/* eslint-disable */
/**
 * Mini-GitHub Files API
 * Servicio para contenido de archivos, commits, descargas y comparacion de branches.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
} from './Identity';

/**
 * 
 * @export
 * @interface UpdateFileBody
 */
export interface UpdateFileBody {
    /**
     * SHA actual del archivo (para control de concurrencia)
     * @type {string}
     * @memberof UpdateFileBody
     */
    sha: string;
    /**
     * Nuevo contenido binario (maximo 10MB)
     * @type {string}
     * @memberof UpdateFileBody
     */
    content: string;
    /**
     * Mensaje del commit
     * @type {string}
     * @memberof UpdateFileBody
     */
    message: string;
    /**
     * Branch destino
     * @type {string}
     * @memberof UpdateFileBody
     */
    branch?: string;
    /**
     * Path original si es rename/move
     * @type {string}
     * @memberof UpdateFileBody
     */
    fromPath?: string;
    /**
     * 
     * @type {Identity}
     * @memberof UpdateFileBody
     */
    author?: Identity;
    /**
     * 
     * @type {Identity}
     * @memberof UpdateFileBody
     */
    committer?: Identity;
}

/**
 * Check if a given object implements the UpdateFileBody interface.
 */
export function instanceOfUpdateFileBody(value: object): boolean {
    if (!('sha' in value)) return false;
    if (!('content' in value)) return false;
    if (!('message' in value)) return false;
    return true;
}

export function UpdateFileBodyFromJSON(json: any): UpdateFileBody {
    return UpdateFileBodyFromJSONTyped(json, false);
}

export function UpdateFileBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFileBody {
    if (json == null) {
        return json;
    }
    return {
        
        'sha': json['sha'],
        'content': json['content'],
        'message': json['message'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'fromPath': json['fromPath'] == null ? undefined : json['fromPath'],
        'author': json['author'] == null ? undefined : IdentityFromJSON(json['author']),
        'committer': json['committer'] == null ? undefined : IdentityFromJSON(json['committer']),
    };
}

export function UpdateFileBodyToJSON(value?: UpdateFileBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sha': value['sha'],
        'content': value['content'],
        'message': value['message'],
        'branch': value['branch'],
        'fromPath': value['fromPath'],
        'author': IdentityToJSON(value['author']),
        'committer': IdentityToJSON(value['committer']),
    };
}

