/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type PolicyRepresentation,
    PolicyRepresentationFromJSON,
    PolicyRepresentationToJSON,
} from '../models/PolicyRepresentation';
import {
    type RolLinkRequest,
    RolLinkRequestFromJSON,
    RolLinkRequestToJSON,
} from '../models/RolLinkRequest';

export interface GetPermissionsRequest {
    clientUuid: string;
    max: number;
    first: number;
}

export interface GetPermissionsByRoleRequest {
    clientUuid: string;
    rolId: string;
}

export interface UpdatePermissionRequest {
    clientUuid: string;
    permissionId: string;
    rolLinkRequest: Array<RolLinkRequest>;
}

/**
 * KeycloakPermissionsControllerApi - interface
 * 
 * @export
 * @interface KeycloakPermissionsControllerApiInterface
 */
export interface KeycloakPermissionsControllerApiInterface {
    /**
     * Creates request options for getPermissions without sending the request
     * @param {string} clientUuid Client UUID
     * @param {number} max Maximum number of permissions to return
     * @param {number} first Index of the first permission to return
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    getPermissionsRequestOpts(requestParameters: GetPermissionsRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets the list of permissions in Keycloak according to the client
     * @summary Gets list of client permissions
     * @param {string} clientUuid Client UUID
     * @param {number} max Maximum number of permissions to return
     * @param {number} first Index of the first permission to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    getPermissionsRaw(requestParameters: GetPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PolicyRepresentation>>>;

    /**
     * Gets the list of permissions in Keycloak according to the client
     * Gets list of client permissions
     */
    getPermissions(requestParameters: GetPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PolicyRepresentation>>;

    /**
     * Creates request options for getPermissionsByRole without sending the request
     * @param {string} clientUuid Client UUID
     * @param {string} rolId Role ID
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    getPermissionsByRoleRequestOpts(requestParameters: GetPermissionsByRoleRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets the list of permissions in Keycloak according to the client and the role
     * @summary Gets list of client permissions by role
     * @param {string} clientUuid Client UUID
     * @param {string} rolId Role ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    getPermissionsByRoleRaw(requestParameters: GetPermissionsByRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PolicyRepresentation>>>;

    /**
     * Gets the list of permissions in Keycloak according to the client and the role
     * Gets list of client permissions by role
     */
    getPermissionsByRole(requestParameters: GetPermissionsByRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PolicyRepresentation>>;

    /**
     * Creates request options for updatePermission without sending the request
     * @param {string} clientUuid Client UUID
     * @param {string} permissionId Permission ID
     * @param {Array<RolLinkRequest>} rolLinkRequest 
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    updatePermissionRequestOpts(requestParameters: UpdatePermissionRequest): Promise<runtime.RequestOpts>;

    /**
     * Modifies a client permission
     * @summary Modifies a client permission
     * @param {string} clientUuid Client UUID
     * @param {string} permissionId Permission ID
     * @param {Array<RolLinkRequest>} rolLinkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakPermissionsControllerApiInterface
     */
    updatePermissionRaw(requestParameters: UpdatePermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Modifies a client permission
     * Modifies a client permission
     */
    updatePermission(requestParameters: UpdatePermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

}

/**
 * 
 */
export class KeycloakPermissionsControllerApi extends runtime.BaseAPI implements KeycloakPermissionsControllerApiInterface {

    /**
     * Creates request options for getPermissions without sending the request
     */
    async getPermissionsRequestOpts(requestParameters: GetPermissionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['clientUuid'] == null) {
            throw new runtime.RequiredError(
                'clientUuid',
                'Required parameter "clientUuid" was null or undefined when calling getPermissions().'
            );
        }

        if (requestParameters['max'] == null) {
            throw new runtime.RequiredError(
                'max',
                'Required parameter "max" was null or undefined when calling getPermissions().'
            );
        }

        if (requestParameters['first'] == null) {
            throw new runtime.RequiredError(
                'first',
                'Required parameter "first" was null or undefined when calling getPermissions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['max'] != null) {
            queryParameters['max'] = requestParameters['max'];
        }

        if (requestParameters['first'] != null) {
            queryParameters['first'] = requestParameters['first'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/permissions/client/{clientUuid}`;
        urlPath = urlPath.replace('{clientUuid}', encodeURIComponent(String(requestParameters['clientUuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the list of permissions in Keycloak according to the client
     * Gets list of client permissions
     */
    async getPermissionsRaw(requestParameters: GetPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PolicyRepresentation>>> {
        const requestOptions = await this.getPermissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PolicyRepresentationFromJSON));
    }

    /**
     * Gets the list of permissions in Keycloak according to the client
     * Gets list of client permissions
     */
    async getPermissions(requestParameters: GetPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PolicyRepresentation>> {
        const response = await this.getPermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPermissionsByRole without sending the request
     */
    async getPermissionsByRoleRequestOpts(requestParameters: GetPermissionsByRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['clientUuid'] == null) {
            throw new runtime.RequiredError(
                'clientUuid',
                'Required parameter "clientUuid" was null or undefined when calling getPermissionsByRole().'
            );
        }

        if (requestParameters['rolId'] == null) {
            throw new runtime.RequiredError(
                'rolId',
                'Required parameter "rolId" was null or undefined when calling getPermissionsByRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/permissions/client/{clientUuid}/rol/{rolId}`;
        urlPath = urlPath.replace('{clientUuid}', encodeURIComponent(String(requestParameters['clientUuid'])));
        urlPath = urlPath.replace('{rolId}', encodeURIComponent(String(requestParameters['rolId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the list of permissions in Keycloak according to the client and the role
     * Gets list of client permissions by role
     */
    async getPermissionsByRoleRaw(requestParameters: GetPermissionsByRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PolicyRepresentation>>> {
        const requestOptions = await this.getPermissionsByRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PolicyRepresentationFromJSON));
    }

    /**
     * Gets the list of permissions in Keycloak according to the client and the role
     * Gets list of client permissions by role
     */
    async getPermissionsByRole(requestParameters: GetPermissionsByRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PolicyRepresentation>> {
        const response = await this.getPermissionsByRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePermission without sending the request
     */
    async updatePermissionRequestOpts(requestParameters: UpdatePermissionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['clientUuid'] == null) {
            throw new runtime.RequiredError(
                'clientUuid',
                'Required parameter "clientUuid" was null or undefined when calling updatePermission().'
            );
        }

        if (requestParameters['permissionId'] == null) {
            throw new runtime.RequiredError(
                'permissionId',
                'Required parameter "permissionId" was null or undefined when calling updatePermission().'
            );
        }

        if (requestParameters['rolLinkRequest'] == null) {
            throw new runtime.RequiredError(
                'rolLinkRequest',
                'Required parameter "rolLinkRequest" was null or undefined when calling updatePermission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/permissions/client/{clientUuid}/permission/{permissionId}`;
        urlPath = urlPath.replace('{clientUuid}', encodeURIComponent(String(requestParameters['clientUuid'])));
        urlPath = urlPath.replace('{permissionId}', encodeURIComponent(String(requestParameters['permissionId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['rolLinkRequest']!.map(RolLinkRequestToJSON),
        };
    }

    /**
     * Modifies a client permission
     * Modifies a client permission
     */
    async updatePermissionRaw(requestParameters: UpdatePermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.updatePermissionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Modifies a client permission
     * Modifies a client permission
     */
    async updatePermission(requestParameters: UpdatePermissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.updatePermissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
