/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ClientRepresentation,
    ClientRepresentationFromJSON,
    ClientRepresentationToJSON,
} from '../models/ClientRepresentation';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';

export interface GetClientsRequest {
    max: number;
    first: number;
}

/**
 * KeycloakClientesControllerApi - interface
 * 
 * @export
 * @interface KeycloakClientesControllerApiInterface
 */
export interface KeycloakClientesControllerApiInterface {
    /**
     * Creates request options for getClients without sending the request
     * @param {number} max Maximum number of clients to return
     * @param {number} first Index of the first client to return
     * @throws {RequiredError}
     * @memberof KeycloakClientesControllerApiInterface
     */
    getClientsRequestOpts(requestParameters: GetClientsRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets the list of clients in Keycloak according to the configured realm
     * @summary Gets list of clients
     * @param {number} max Maximum number of clients to return
     * @param {number} first Index of the first client to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakClientesControllerApiInterface
     */
    getClientsRaw(requestParameters: GetClientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ClientRepresentation>>>;

    /**
     * Gets the list of clients in Keycloak according to the configured realm
     * Gets list of clients
     */
    getClients(requestParameters: GetClientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ClientRepresentation>>;

}

/**
 * 
 */
export class KeycloakClientesControllerApi extends runtime.BaseAPI implements KeycloakClientesControllerApiInterface {

    /**
     * Creates request options for getClients without sending the request
     */
    async getClientsRequestOpts(requestParameters: GetClientsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['max'] == null) {
            throw new runtime.RequiredError(
                'max',
                'Required parameter "max" was null or undefined when calling getClients().'
            );
        }

        if (requestParameters['first'] == null) {
            throw new runtime.RequiredError(
                'first',
                'Required parameter "first" was null or undefined when calling getClients().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['max'] != null) {
            queryParameters['max'] = requestParameters['max'];
        }

        if (requestParameters['first'] != null) {
            queryParameters['first'] = requestParameters['first'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/clients`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the list of clients in Keycloak according to the configured realm
     * Gets list of clients
     */
    async getClientsRaw(requestParameters: GetClientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ClientRepresentation>>> {
        const requestOptions = await this.getClientsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClientRepresentationFromJSON));
    }

    /**
     * Gets the list of clients in Keycloak according to the configured realm
     * Gets list of clients
     */
    async getClients(requestParameters: GetClientsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ClientRepresentation>> {
        const response = await this.getClientsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
