/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type RoleRepresentation,
    RoleRepresentationFromJSON,
    RoleRepresentationToJSON,
} from '../models/RoleRepresentation';

export interface GetClientRolesRequest {
    clientUuid: string;
    max: number;
    first: number;
}

export interface GetRealmRolesRequest {
    max: number;
    first: number;
}

export interface GetRoleRequest {
    rolId: string;
}

/**
 * KeycloakRolesControllerApi - interface
 * 
 * @export
 * @interface KeycloakRolesControllerApiInterface
 */
export interface KeycloakRolesControllerApiInterface {
    /**
     * Creates request options for getClientRoles without sending the request
     * @param {string} clientUuid Client UUID
     * @param {number} max Maximum number of roles to return
     * @param {number} first Index of the first role to return
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getClientRolesRequestOpts(requestParameters: GetClientRolesRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets the list of roles in Keycloak according to the client
     * @summary Gets list of client roles
     * @param {string} clientUuid Client UUID
     * @param {number} max Maximum number of roles to return
     * @param {number} first Index of the first role to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getClientRolesRaw(requestParameters: GetClientRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleRepresentation>>>;

    /**
     * Gets the list of roles in Keycloak according to the client
     * Gets list of client roles
     */
    getClientRoles(requestParameters: GetClientRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleRepresentation>>;

    /**
     * Creates request options for getRealmRoles without sending the request
     * @param {number} max Maximum number of roles to return
     * @param {number} first Index of the first role to return
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getRealmRolesRequestOpts(requestParameters: GetRealmRolesRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets the list of roles in Keycloak according to the configured realm
     * @summary Gets list of roles from the realm
     * @param {number} max Maximum number of roles to return
     * @param {number} first Index of the first role to return
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getRealmRolesRaw(requestParameters: GetRealmRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleRepresentation>>>;

    /**
     * Gets the list of roles in Keycloak according to the configured realm
     * Gets list of roles from the realm
     */
    getRealmRoles(requestParameters: GetRealmRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleRepresentation>>;

    /**
     * Creates request options for getRole without sending the request
     * @param {string} rolId ID of the role to get
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getRoleRequestOpts(requestParameters: GetRoleRequest): Promise<runtime.RequestOpts>;

    /**
     * Gets a specific role from Keycloak by its ID
     * @summary Gets client role
     * @param {string} rolId ID of the role to get
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KeycloakRolesControllerApiInterface
     */
    getRoleRaw(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleRepresentation>>;

    /**
     * Gets a specific role from Keycloak by its ID
     * Gets client role
     */
    getRole(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleRepresentation>;

}

/**
 * 
 */
export class KeycloakRolesControllerApi extends runtime.BaseAPI implements KeycloakRolesControllerApiInterface {

    /**
     * Creates request options for getClientRoles without sending the request
     */
    async getClientRolesRequestOpts(requestParameters: GetClientRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['clientUuid'] == null) {
            throw new runtime.RequiredError(
                'clientUuid',
                'Required parameter "clientUuid" was null or undefined when calling getClientRoles().'
            );
        }

        if (requestParameters['max'] == null) {
            throw new runtime.RequiredError(
                'max',
                'Required parameter "max" was null or undefined when calling getClientRoles().'
            );
        }

        if (requestParameters['first'] == null) {
            throw new runtime.RequiredError(
                'first',
                'Required parameter "first" was null or undefined when calling getClientRoles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['max'] != null) {
            queryParameters['max'] = requestParameters['max'];
        }

        if (requestParameters['first'] != null) {
            queryParameters['first'] = requestParameters['first'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/roles/client/{clientUuid}`;
        urlPath = urlPath.replace('{clientUuid}', encodeURIComponent(String(requestParameters['clientUuid'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the list of roles in Keycloak according to the client
     * Gets list of client roles
     */
    async getClientRolesRaw(requestParameters: GetClientRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleRepresentation>>> {
        const requestOptions = await this.getClientRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleRepresentationFromJSON));
    }

    /**
     * Gets the list of roles in Keycloak according to the client
     * Gets list of client roles
     */
    async getClientRoles(requestParameters: GetClientRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleRepresentation>> {
        const response = await this.getClientRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRealmRoles without sending the request
     */
    async getRealmRolesRequestOpts(requestParameters: GetRealmRolesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['max'] == null) {
            throw new runtime.RequiredError(
                'max',
                'Required parameter "max" was null or undefined when calling getRealmRoles().'
            );
        }

        if (requestParameters['first'] == null) {
            throw new runtime.RequiredError(
                'first',
                'Required parameter "first" was null or undefined when calling getRealmRoles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['max'] != null) {
            queryParameters['max'] = requestParameters['max'];
        }

        if (requestParameters['first'] != null) {
            queryParameters['first'] = requestParameters['first'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/roles/realm`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets the list of roles in Keycloak according to the configured realm
     * Gets list of roles from the realm
     */
    async getRealmRolesRaw(requestParameters: GetRealmRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleRepresentation>>> {
        const requestOptions = await this.getRealmRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleRepresentationFromJSON));
    }

    /**
     * Gets the list of roles in Keycloak according to the configured realm
     * Gets list of roles from the realm
     */
    async getRealmRoles(requestParameters: GetRealmRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleRepresentation>> {
        const response = await this.getRealmRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRole without sending the request
     */
    async getRoleRequestOpts(requestParameters: GetRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['rolId'] == null) {
            throw new runtime.RequiredError(
                'rolId',
                'Required parameter "rolId" was null or undefined when calling getRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/keycloak/roles/{rolId}`;
        urlPath = urlPath.replace('{rolId}', encodeURIComponent(String(requestParameters['rolId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gets a specific role from Keycloak by its ID
     * Gets client role
     */
    async getRoleRaw(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleRepresentation>> {
        const requestOptions = await this.getRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleRepresentationFromJSON(jsonValue));
    }

    /**
     * Gets a specific role from Keycloak by its ID
     * Gets client role
     */
    async getRole(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleRepresentation> {
        const response = await this.getRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
