/* tslint:disable */
/* eslint-disable */
/**
 * MS Users API
 * Github-users-ms
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DeleteResponse,
    DeleteResponseFromJSON,
    DeleteResponseToJSON,
} from '../models/DeleteResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type PageUserResponse,
    PageUserResponseFromJSON,
    PageUserResponseToJSON,
} from '../models/PageUserResponse';
import {
    type SearchRequest,
    SearchRequestFromJSON,
    SearchRequestToJSON,
} from '../models/SearchRequest';
import {
    type UserRequest,
    UserRequestFromJSON,
    UserRequestToJSON,
} from '../models/UserRequest';
import {
    type UserResponse,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/UserResponse';

export interface CreateUserRequest {
    userRequest: UserRequest;
}

export interface DeleteUserRequest {
    userId: string;
}

export interface EditUserRequest {
    userId: string;
    userRequest: UserRequest;
}

export interface GetListUsersRequest {
    pageSize: number;
    page: number;
}

export interface GetUserRequest {
    userId: string;
}

export interface SearchUsersRequest {
    searchRequest: SearchRequest;
}

/**
 * UserControllerApi - interface
 * 
 * @export
 * @interface UserControllerApiInterface
 */
export interface UserControllerApiInterface {
    /**
     * Creates request options for createUser without sending the request
     * @param {UserRequest} userRequest Data needed to create a new user
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    createUserRequestOpts(requestParameters: CreateUserRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows the creation of a new user by providing the required data in the request body. If the operation is successful, it returns the details of the created user.
     * @summary Register a new user
     * @param {UserRequest} userRequest Data needed to create a new user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * This endpoint allows the creation of a new user by providing the required data in the request body. If the operation is successful, it returns the details of the created user.
     * Register a new user
     */
    createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse>;

    /**
     * Creates request options for deleteUser without sending the request
     * @param {string} userId Identifier of the user
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    deleteUserRequestOpts(requestParameters: DeleteUserRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows you to permanently delete a user. It is necessary to provide the `userId` parameter, which uniquely identifies the user you want to delete.
     * @summary Delete an existing user
     * @param {string} userId Identifier of the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>>;

    /**
     * This endpoint allows you to permanently delete a user. It is necessary to provide the `userId` parameter, which uniquely identifies the user you want to delete.
     * Delete an existing user
     */
    deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse>;

    /**
     * Creates request options for editUser without sending the request
     * @param {string} userId Unique identifier of the user
     * @param {UserRequest} userRequest Data needed to edit an existing user
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    editUserRequestOpts(requestParameters: EditUserRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows you to update the details of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the user to be edited.
     * @summary Edit an existing user
     * @param {string} userId Unique identifier of the user
     * @param {UserRequest} userRequest Data needed to edit an existing user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    editUserRaw(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * This endpoint allows you to update the details of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the user to be edited.
     * Edit an existing user
     */
    editUser(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse>;

    /**
     * Creates request options for getListUsers without sending the request
     * @param {number} pageSize Number of records that will be displayed per page.
     * @param {number} page Number of the page you want to query.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    getListUsersRequestOpts(requestParameters: GetListUsersRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows you to retrieve a paginated list of registered users. It is mandatory to provide the `page` and `pageSize` parameters to control pagination.
     * @summary Get paginated list of users
     * @param {number} pageSize Number of records that will be displayed per page.
     * @param {number} page Number of the page you want to query.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    getListUsersRaw(requestParameters: GetListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageUserResponse>>;

    /**
     * This endpoint allows you to retrieve a paginated list of registered users. It is mandatory to provide the `page` and `pageSize` parameters to control pagination.
     * Get paginated list of users
     */
    getListUsers(requestParameters: GetListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageUserResponse>;

    /**
     * Creates request options for getUser without sending the request
     * @param {string} userId Unique identifier of the user (UUID)
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    getUserRequestOpts(requestParameters: GetUserRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows you to retrieve detailed information of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the requested user.
     * @summary Get details of a specific user
     * @param {string} userId Unique identifier of the user (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>>;

    /**
     * This endpoint allows you to retrieve detailed information of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the requested user.
     * Get details of a specific user
     */
    getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse>;

    /**
     * Creates request options for searchUsers without sending the request
     * @param {SearchRequest} searchRequest Data needed to search for users by filter
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    searchUsersRequestOpts(requestParameters: SearchUsersRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows you to search for users by filter. It is necessary to provide the `filter` parameter, which uniquely identifies the user to be filtered.
     * @summary Search users by filter
     * @param {SearchRequest} searchRequest Data needed to search for users by filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserControllerApiInterface
     */
    searchUsersRaw(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageUserResponse>>;

    /**
     * This endpoint allows you to search for users by filter. It is necessary to provide the `filter` parameter, which uniquely identifies the user to be filtered.
     * Search users by filter
     */
    searchUsers(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageUserResponse>;

}

/**
 * 
 */
export class UserControllerApi extends runtime.BaseAPI implements UserControllerApiInterface {

    /**
     * Creates request options for createUser without sending the request
     */
    async createUserRequestOpts(requestParameters: CreateUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userRequest'] == null) {
            throw new runtime.RequiredError(
                'userRequest',
                'Required parameter "userRequest" was null or undefined when calling createUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRequestToJSON(requestParameters['userRequest']),
        };
    }

    /**
     * This endpoint allows the creation of a new user by providing the required data in the request body. If the operation is successful, it returns the details of the created user.
     * Register a new user
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.createUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows the creation of a new user by providing the required data in the request body. If the operation is successful, it returns the details of the created user.
     * Register a new user
     */
    async createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteUser without sending the request
     */
    async deleteUserRequestOpts(requestParameters: DeleteUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint allows you to permanently delete a user. It is necessary to provide the `userId` parameter, which uniquely identifies the user you want to delete.
     * Delete an existing user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteResponse>> {
        const requestOptions = await this.deleteUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to permanently delete a user. It is necessary to provide the `userId` parameter, which uniquely identifies the user you want to delete.
     * Delete an existing user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteResponse> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for editUser without sending the request
     */
    async editUserRequestOpts(requestParameters: EditUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling editUser().'
            );
        }

        if (requestParameters['userRequest'] == null) {
            throw new runtime.RequiredError(
                'userRequest',
                'Required parameter "userRequest" was null or undefined when calling editUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserRequestToJSON(requestParameters['userRequest']),
        };
    }

    /**
     * This endpoint allows you to update the details of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the user to be edited.
     * Edit an existing user
     */
    async editUserRaw(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.editUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to update the details of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the user to be edited.
     * Edit an existing user
     */
    async editUser(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.editUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getListUsers without sending the request
     */
    async getListUsersRequestOpts(requestParameters: GetListUsersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pageSize'] == null) {
            throw new runtime.RequiredError(
                'pageSize',
                'Required parameter "pageSize" was null or undefined when calling getListUsers().'
            );
        }

        if (requestParameters['page'] == null) {
            throw new runtime.RequiredError(
                'page',
                'Required parameter "page" was null or undefined when calling getListUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint allows you to retrieve a paginated list of registered users. It is mandatory to provide the `page` and `pageSize` parameters to control pagination.
     * Get paginated list of users
     */
    async getListUsersRaw(requestParameters: GetListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageUserResponse>> {
        const requestOptions = await this.getListUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageUserResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to retrieve a paginated list of registered users. It is mandatory to provide the `page` and `pageSize` parameters to control pagination.
     * Get paginated list of users
     */
    async getListUsers(requestParameters: GetListUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageUserResponse> {
        const response = await this.getListUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUser without sending the request
     */
    async getUserRequestOpts(requestParameters: GetUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/{userId}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint allows you to retrieve detailed information of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the requested user.
     * Get details of a specific user
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.getUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to retrieve detailed information of a registered user. It is necessary to provide the `userId` parameter, which uniquely identifies the requested user.
     * Get details of a specific user
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchUsers without sending the request
     */
    async searchUsersRequestOpts(requestParameters: SearchUsersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling searchUsers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/users/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        };
    }

    /**
     * This endpoint allows you to search for users by filter. It is necessary to provide the `filter` parameter, which uniquely identifies the user to be filtered.
     * Search users by filter
     */
    async searchUsersRaw(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageUserResponse>> {
        const requestOptions = await this.searchUsersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageUserResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to search for users by filter. It is necessary to provide the `filter` parameter, which uniquely identifies the user to be filtered.
     * Search users by filter
     */
    async searchUsers(requestParameters: SearchUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageUserResponse> {
        const response = await this.searchUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
